# Generated by Django 6.0.3 on 2026-04-03 03:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Turma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "turno",
                    models.CharField(
                        choices=[
                            ("manha", "Manhã"),
                            ("tarde", "Tarde"),
                            ("noite", "Noite"),
                        ],
                        max_length=20,
                    ),
                ),
                ("ano", models.IntegerField()),
            ],
            options={
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Aluno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_completo", models.CharField(max_length=255)),
                (
                    "cpf",
                    models.CharField(
                        db_index=True,
                        max_length=14,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$"
                            )
                        ],
                    ),
                ),
                ("data_nascimento", models.DateField(blank=True, null=True)),
                ("naturalidade", models.CharField(blank=True, max_length=100)),
                ("telefone", models.CharField(blank=True, max_length=20)),
                ("responsavel1", models.CharField(blank=True, max_length=255)),
                ("responsavel2", models.CharField(blank=True, max_length=255)),
                ("cep", models.CharField(blank=True, max_length=9)),
                (
                    "estado",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("AC", "AC"),
                            ("AL", "AL"),
                            ("AP", "AP"),
                            ("AM", "AM"),
                            ("BA", "BA"),
                            ("CE", "CE"),
                            ("DF", "DF"),
                            ("ES", "ES"),
                            ("GO", "GO"),
                            ("MA", "MA"),
                            ("MT", "MT"),
                            ("MS", "MS"),
                            ("MG", "MG"),
                            ("PA", "PA"),
                            ("PB", "PB"),
                            ("PR", "PR"),
                            ("PE", "PE"),
                            ("PI", "PI"),
                            ("RJ", "RJ"),
                            ("RN", "RN"),
                            ("RS", "RS"),
                            ("RO", "RO"),
                            ("RR", "RR"),
                            ("SC", "SC"),
                            ("SP", "SP"),
                            ("SE", "SE"),
                            ("TO", "TO"),
                        ],
                        max_length=2,
                    ),
                ),
                ("cidade", models.CharField(blank=True, max_length=100)),
                ("bairro", models.CharField(blank=True, max_length=100)),
                ("logradouro", models.CharField(blank=True, max_length=255)),
                ("numero", models.CharField(blank=True, max_length=10)),
                ("complemento", models.CharField(blank=True, max_length=255)),
                ("possui_necessidade_especial", models.BooleanField(default=False)),
                ("descricao_necessidade", models.TextField(blank=True)),
                (
                    "foto",
                    models.ImageField(blank=True, null=True, upload_to="fotos/alunos/"),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aluno",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "turma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alunos",
                        to="core.turma",
                    ),
                ),
            ],
            options={
                "ordering": ["nome_completo"],
            },
        ),
        migrations.CreateModel(
            name="Gestor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_completo", models.CharField(max_length=255)),
                (
                    "cpf",
                    models.CharField(
                        db_index=True,
                        max_length=14,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$"
                            )
                        ],
                    ),
                ),
                (
                    "cargo",
                    models.CharField(
                        choices=[
                            ("diretor", "Diretor"),
                            ("vice_diretor", "Vice-Diretor"),
                            ("secretario", "Secretário"),
                            ("coordenador", "Coordenador"),
                        ],
                        max_length=20,
                    ),
                ),
                ("telefone", models.CharField(blank=True, max_length=20)),
                ("cep", models.CharField(blank=True, max_length=9)),
                (
                    "estado",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("AC", "AC"),
                            ("AL", "AL"),
                            ("AP", "AP"),
                            ("AM", "AM"),
                            ("BA", "BA"),
                            ("CE", "CE"),
                            ("DF", "DF"),
                            ("ES", "ES"),
                            ("GO", "GO"),
                            ("MA", "MA"),
                            ("MT", "MT"),
                            ("MS", "MS"),
                            ("MG", "MG"),
                            ("PA", "PA"),
                            ("PB", "PB"),
                            ("PR", "PR"),
                            ("PE", "PE"),
                            ("PI", "PI"),
                            ("RJ", "RJ"),
                            ("RN", "RN"),
                            ("RS", "RS"),
                            ("RO", "RO"),
                            ("RR", "RR"),
                            ("SC", "SC"),
                            ("SP", "SP"),
                            ("SE", "SE"),
                            ("TO", "TO"),
                        ],
                        max_length=2,
                    ),
                ),
                ("cidade", models.CharField(blank=True, max_length=100)),
                ("bairro", models.CharField(blank=True, max_length=100)),
                ("logradouro", models.CharField(blank=True, max_length=255)),
                ("numero", models.CharField(blank=True, max_length=10)),
                ("complemento", models.CharField(blank=True, max_length=255)),
                (
                    "foto",
                    models.ImageField(
                        blank=True, null=True, upload_to="fotos/gestores/"
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gestor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["nome_completo"],
            },
        ),
        migrations.CreateModel(
            name="Professor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_completo", models.CharField(max_length=255)),
                (
                    "cpf",
                    models.CharField(
                        db_index=True,
                        max_length=14,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$"
                            )
                        ],
                    ),
                ),
                ("data_nascimento", models.DateField(blank=True, null=True)),
                ("telefone", models.CharField(blank=True, max_length=20)),
                ("cep", models.CharField(blank=True, max_length=9)),
                (
                    "estado",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("AC", "AC"),
                            ("AL", "AL"),
                            ("AP", "AP"),
                            ("AM", "AM"),
                            ("BA", "BA"),
                            ("CE", "CE"),
                            ("DF", "DF"),
                            ("ES", "ES"),
                            ("GO", "GO"),
                            ("MA", "MA"),
                            ("MT", "MT"),
                            ("MS", "MS"),
                            ("MG", "MG"),
                            ("PA", "PA"),
                            ("PB", "PB"),
                            ("PR", "PR"),
                            ("PE", "PE"),
                            ("PI", "PI"),
                            ("RJ", "RJ"),
                            ("RN", "RN"),
                            ("RS", "RS"),
                            ("RO", "RO"),
                            ("RR", "RR"),
                            ("SC", "SC"),
                            ("SP", "SP"),
                            ("SE", "SE"),
                            ("TO", "TO"),
                        ],
                        max_length=2,
                    ),
                ),
                ("cidade", models.CharField(blank=True, max_length=100)),
                ("bairro", models.CharField(blank=True, max_length=100)),
                ("logradouro", models.CharField(blank=True, max_length=255)),
                ("numero", models.CharField(blank=True, max_length=10)),
                ("complemento", models.CharField(blank=True, max_length=255)),
                ("formacao", models.CharField(blank=True, max_length=255)),
                ("especializacao", models.CharField(blank=True, max_length=255)),
                ("area_atuacao", models.CharField(blank=True, max_length=255)),
                (
                    "foto",
                    models.ImageField(
                        blank=True, null=True, upload_to="fotos/professores/"
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="professor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["nome_completo"],
            },
        ),
        migrations.CreateModel(
            name="Disciplina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "professor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disciplinas",
                        to="core.professor",
                    ),
                ),
                (
                    "turma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disciplinas",
                        to="core.turma",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Frequencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField()),
                ("presente", models.BooleanField(default=True)),
                ("observacao", models.CharField(blank=True, max_length=255)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="frequencias",
                        to="core.aluno",
                    ),
                ),
                (
                    "disciplina",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="frequencias",
                        to="core.disciplina",
                    ),
                ),
            ],
            options={
                "ordering": ["-data"],
                "unique_together": {("aluno", "disciplina", "data")},
            },
        ),
        migrations.CreateModel(
            name="Nota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "bimestre",
                    models.IntegerField(
                        choices=[
                            (1, "1º Bimestre"),
                            (2, "2º Bimestre"),
                            (3, "3º Bimestre"),
                            (4, "4º Bimestre"),
                        ]
                    ),
                ),
                ("data_lancamento", models.DateField(auto_now_add=True)),
                ("observacao", models.CharField(blank=True, max_length=255)),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notas",
                        to="core.aluno",
                    ),
                ),
                (
                    "disciplina",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notas",
                        to="core.disciplina",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nota",
                "verbose_name_plural": "Notas",
                "ordering": ["aluno", "disciplina", "bimestre"],
                "unique_together": {("aluno", "disciplina", "bimestre")},
            },
        ),
        migrations.CreateModel(
            name="GradeHorario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dia_semana",
                    models.CharField(
                        choices=[
                            ("segunda", "Segunda-feira"),
                            ("terca", "Terça-feira"),
                            ("quarta", "Quarta-feira"),
                            ("quinta", "Quinta-feira"),
                            ("sexta", "Sexta-feira"),
                        ],
                        default="segunda",
                        max_length=10,
                    ),
                ),
                ("horario_inicio", models.TimeField(blank=True, null=True)),
                ("horario_fim", models.TimeField(blank=True, null=True)),
                ("observacao", models.CharField(blank=True, max_length=255)),
                (
                    "disciplina",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="grade_horarios",
                        to="core.disciplina",
                    ),
                ),
                (
                    "professor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="grade_horarios",
                        to="core.professor",
                    ),
                ),
                (
                    "turma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grade_horarios",
                        to="core.turma",
                    ),
                ),
            ],
            options={
                "verbose_name": "Horário",
                "verbose_name_plural": "Grade de Horários",
                "ordering": ["turma", "dia_semana", "horario_inicio"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("turma", "dia_semana", "horario_inicio"),
                        name="unique_horario_turma",
                    )
                ],
            },
        ),
    ]
