# Generated by Django 6.0.3 on 2026-04-09 21:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoCalendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(help_text='Data do evento', unique=True)),
                ('tipo', models.CharField(choices=[('DI_LETIVO', 'Dia Letivo'), ('FERIADO', 'Feriado'), ('PROVA', 'Semana de Prova'), ('SABADO_LETIVO', 'Sábado Letivo'), ('RECESSO', 'Recesso / Férias'), ('FIM_SEMANA', 'Final de Semana')], default='DI_LETIVO', max_length=20)),
                ('descricao', models.CharField(blank=True, help_text='Descrição (ex: Feriado Local, Nome da Prova)', max_length=255)),
                ('aula_suspensa', models.BooleanField(default=False, help_text='Indica se as aulas estão suspensas neste dia')),
            ],
            options={
                'verbose_name': 'Evento de Calendário',
                'verbose_name_plural': 'Eventos de Calendário',
                'ordering': ['data'],
            },
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='professor',
            field=models.ForeignKey(help_text='Professor responsável', on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas', to='core.professor'),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='turma',
            field=models.ForeignKey(help_text='Turma associada', on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas', to='core.turma'),
        ),
        migrations.AlterField(
            model_name='frequencia',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frequencias', to='core.aluno'),
        ),
        migrations.AlterField(
            model_name='frequencia',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='frequencia',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frequencias', to='core.disciplina'),
        ),
        migrations.AlterField(
            model_name='frequencia',
            name='observacao',
            field=models.CharField(blank=True, help_text='Observações', max_length=255),
        ),
        migrations.AlterField(
            model_name='nota',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='core.aluno'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='data_lancamento',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='nota',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='core.disciplina'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='nota1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='nota',
            name='nota2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='nota',
            name='nota3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='nota',
            name='nota4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='nota',
            name='observacao',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
