# Generated by Django 5.0.5 on 2026-03-24 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aluno",
            name="bairro",
        ),
        migrations.RemoveField(
            model_name="aluno",
            name="cep",
        ),
        migrations.RemoveField(
            model_name="aluno",
            name="data_nascimento",
        ),
        migrations.RemoveField(
            model_name="aluno",
            name="descricao_necessidade",
        ),
        migrations.RemoveField(
            model_name="aluno",
            name="filiacao_1",
        ),
        migrations.RemoveField(
            model_name="aluno",
            name="filiacao_2",
        ),
        migrations.RemoveField(
            model_name="aluno",
            name="logradouro",
        ),
        migrations.RemoveField(
            model_name="aluno",
            name="naturalidade",
        ),
        migrations.RemoveField(
            model_name="aluno",
            name="necessidade_especial",
        ),
        migrations.RemoveField(
            model_name="aluno",
            name="numero",
        ),
        migrations.RemoveField(
            model_name="aluno",
            name="telefone",
        ),
        migrations.RemoveField(
            model_name="gestor",
            name="cep",
        ),
        migrations.RemoveField(
            model_name="gestor",
            name="data_nascimento",
        ),
        migrations.RemoveField(
            model_name="gestor",
            name="telefone",
        ),
        migrations.RemoveField(
            model_name="professor",
            name="area_atuacao",
        ),
        migrations.RemoveField(
            model_name="professor",
            name="bairro",
        ),
        migrations.RemoveField(
            model_name="professor",
            name="cep",
        ),
        migrations.RemoveField(
            model_name="professor",
            name="complemento",
        ),
        migrations.RemoveField(
            model_name="professor",
            name="especializacao",
        ),
        migrations.RemoveField(
            model_name="professor",
            name="formacao",
        ),
        migrations.RemoveField(
            model_name="professor",
            name="logradouro",
        ),
        migrations.RemoveField(
            model_name="professor",
            name="numero",
        ),
    ]
