# Generated by Django 6.0.3 on 2026-04-03 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="nota",
            options={
                "ordering": ["aluno", "disciplina"],
                "verbose_name": "Nota",
                "verbose_name_plural": "Notas",
            },
        ),
        migrations.AlterUniqueTogether(
            name="nota",
            unique_together={("aluno", "disciplina")},
        ),
        migrations.AddField(
            model_name="gestor",
            name="data_nascimento",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="nota",
            name="nota1",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="nota",
            name="nota2",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="nota",
            name="nota3",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="nota",
            name="nota4",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.RemoveField(
            model_name="nota",
            name="bimestre",
        ),
        migrations.RemoveField(
            model_name="nota",
            name="valor",
        ),
    ]
