# Generated by Django 6.0.3 on 2026-04-03 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_nota_options_alter_nota_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gradehorario",
            options={
                "verbose_name": "Grade de Horários",
                "verbose_name_plural": "Grades de Horários",
            },
        ),
        migrations.RemoveConstraint(
            model_name="gradehorario",
            name="unique_horario_turma",
        ),
        migrations.AddField(
            model_name="gradehorario",
            name="dados",
            field=models.JSONField(
                default=dict,
                help_text="Mapa dia → lista de nomes de disciplina por slot do turno.",
            ),
        ),
        migrations.AlterField(
            model_name="gradehorario",
            name="turma",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grade_horario",
                to="core.turma",
            ),
        ),
        migrations.RemoveField(
            model_name="gradehorario",
            name="dia_semana",
        ),
        migrations.RemoveField(
            model_name="gradehorario",
            name="disciplina",
        ),
        migrations.RemoveField(
            model_name="gradehorario",
            name="horario_fim",
        ),
        migrations.RemoveField(
            model_name="gradehorario",
            name="horario_inicio",
        ),
        migrations.RemoveField(
            model_name="gradehorario",
            name="observacao",
        ),
        migrations.RemoveField(
            model_name="gradehorario",
            name="professor",
        ),
    ]
