# Generated by Django 5.0.5 on 2026-03-24 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_aluno_bairro_remove_aluno_cep_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="professor",
            options={},
        ),
        migrations.AddField(
            model_name="professor",
            name="area_atuacao",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="professor",
            name="bairro",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="professor",
            name="cep",
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AddField(
            model_name="professor",
            name="complemento",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="professor",
            name="especializacao",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="professor",
            name="formacao",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="professor",
            name="logradouro",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="professor",
            name="numero",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name="professor",
            name="cpf",
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
