# Generated by Django 6.0.3 on 2026-04-03 17:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_gradehorario_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aluno",
            options={
                "ordering": ["nome_completo"],
                "verbose_name": "Aluno",
                "verbose_name_plural": "Alunos",
            },
        ),
        migrations.AlterModelOptions(
            name="disciplina",
            options={
                "verbose_name": "Disciplina",
                "verbose_name_plural": "Disciplinas",
            },
        ),
        migrations.AlterModelOptions(
            name="frequencia",
            options={
                "ordering": ["-data"],
                "verbose_name": "Frequência",
                "verbose_name_plural": "Frequências",
            },
        ),
        migrations.AlterModelOptions(
            name="gestor",
            options={
                "ordering": ["nome_completo"],
                "verbose_name": "Gestor",
                "verbose_name_plural": "Gestores",
            },
        ),
        migrations.AlterModelOptions(
            name="professor",
            options={
                "ordering": ["nome_completo"],
                "verbose_name": "Professor",
                "verbose_name_plural": "Professores",
            },
        ),
        migrations.AlterModelOptions(
            name="turma",
            options={
                "ordering": ["nome"],
                "verbose_name": "Turma",
                "verbose_name_plural": "Turmas",
            },
        ),
        migrations.AlterField(
            model_name="aluno",
            name="atualizado_em",
            field=models.DateTimeField(
                auto_now=True, help_text="Data da última atualização"
            ),
        ),
        migrations.AlterField(
            model_name="aluno",
            name="bairro",
            field=models.CharField(blank=True, help_text="Bairro", max_length=100),
        ),
        migrations.AlterField(
            model_name="aluno",
            name="cep",
            field=models.CharField(blank=True, help_text="CEP", max_length=9),
        ),
        migrations.AlterField(
            model_name="aluno",
            name="cidade",
            field=models.CharField(blank=True, help_text="Cidade", max_length=100),
        ),
        migrations.AlterField(
            model_name="aluno",
            name="complemento",
            field=models.CharField(
                blank=True, help_text="Complemento do endereço", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="aluno",
            name="cpf",
            field=models.CharField(
                db_index=True,
                help_text="CPF no formato XXX.XXX.XXX-XX",
                max_length=14,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="aluno",
            name="criado_em",
            field=models.DateTimeField(auto_now_add=True, help_text="Data de criação"),
        ),
        migrations.AlterField(
            model_name="aluno",
            name="data_nascimento",
            field=models.DateField(
                blank=True, help_text="Data de nascimento", null=True
            ),
        ),
        migrations.AlterField(
            model_name="aluno",
            name="descricao_necessidade",
            field=models.TextField(
                blank=True, help_text="Descrição da necessidade especial"
            ),
        ),
        migrations.AlterField(
            model_name="aluno",
            name="estado",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AC", "AC"),
                    ("AL", "AL"),
                    ("AP", "AP"),
                    ("AM", "AM"),
                    ("BA", "BA"),
                    ("CE", "CE"),
                    ("DF", "DF"),
                    ("ES", "ES"),
                    ("GO", "GO"),
                    ("MA", "MA"),
                    ("MT", "MT"),
                    ("MS", "MS"),
                    ("MG", "MG"),
                    ("PA", "PA"),
                    ("PB", "PB"),
                    ("PR", "PR"),
                    ("PE", "PE"),
                    ("PI", "PI"),
                    ("RJ", "RJ"),
                    ("RN", "RN"),
                    ("RS", "RS"),
                    ("RO", "RO"),
                    ("RR", "RR"),
                    ("SC", "SC"),
                    ("SP", "SP"),
                    ("SE", "SE"),
                    ("TO", "TO"),
                ],
                help_text="Estado (UF)",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="aluno",
            name="foto",
            field=models.ImageField(
                blank=True,
                help_text="Foto da pessoa",
                null=True,
                upload_to="fotos/pessoas/",
            ),
        ),
        migrations.AlterField(
            model_name="aluno",
            name="logradouro",
            field=models.CharField(blank=True, help_text="Logradouro", max_length=255),
        ),
        migrations.AlterField(
            model_name="aluno",
            name="naturalidade",
            field=models.CharField(
                blank=True, help_text="Cidade de origem", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="aluno",
            name="nome_completo",
            field=models.CharField(help_text="Nome completo da pessoa", max_length=255),
        ),
        migrations.AlterField(
            model_name="aluno",
            name="numero",
            field=models.CharField(
                blank=True, help_text="Número do endereço", max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="aluno",
            name="possui_necessidade_especial",
            field=models.BooleanField(
                default=False, help_text="Indica se possui necessidade especial"
            ),
        ),
        migrations.AlterField(
            model_name="aluno",
            name="responsavel1",
            field=models.CharField(
                blank=True, help_text="Nome do responsável principal", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="aluno",
            name="responsavel2",
            field=models.CharField(
                blank=True, help_text="Nome do segundo responsável", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="aluno",
            name="telefone",
            field=models.CharField(
                blank=True, help_text="Número de telefone", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="aluno",
            name="turma",
            field=models.ForeignKey(
                help_text="Turma do aluno",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alunos",
                to="core.turma",
            ),
        ),
        migrations.AlterField(
            model_name="aluno",
            name="user",
            field=models.OneToOneField(
                help_text="Usuário vinculado ao aluno",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="aluno",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="disciplina",
            name="nome",
            field=models.CharField(help_text="Nome da disciplina", max_length=100),
        ),
        migrations.AlterField(
            model_name="disciplina",
            name="professor",
            field=models.ForeignKey(
                help_text="Professor responsável pela disciplina",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="disciplinas",
                to="core.professor",
            ),
        ),
        migrations.AlterField(
            model_name="disciplina",
            name="turma",
            field=models.ForeignKey(
                help_text="Turma associada à disciplina",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="disciplinas",
                to="core.turma",
            ),
        ),
        migrations.AlterField(
            model_name="frequencia",
            name="aluno",
            field=models.ForeignKey(
                help_text="Aluno registrado na frequência",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="frequencias",
                to="core.aluno",
            ),
        ),
        migrations.AlterField(
            model_name="frequencia",
            name="criado_em",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Data de criação do registro"
            ),
        ),
        migrations.AlterField(
            model_name="frequencia",
            name="data",
            field=models.DateField(help_text="Data da frequência"),
        ),
        migrations.AlterField(
            model_name="frequencia",
            name="disciplina",
            field=models.ForeignKey(
                help_text="Disciplina da frequência",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="frequencias",
                to="core.disciplina",
            ),
        ),
        migrations.AlterField(
            model_name="frequencia",
            name="observacao",
            field=models.CharField(
                blank=True, help_text="Observações sobre a frequência", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="frequencia",
            name="presente",
            field=models.BooleanField(
                default=True, help_text="Presença (True) ou Falta (False)"
            ),
        ),
        migrations.AlterField(
            model_name="gestor",
            name="atualizado_em",
            field=models.DateTimeField(
                auto_now=True, help_text="Data da última atualização"
            ),
        ),
        migrations.AlterField(
            model_name="gestor",
            name="bairro",
            field=models.CharField(blank=True, help_text="Bairro", max_length=100),
        ),
        migrations.AlterField(
            model_name="gestor",
            name="cargo",
            field=models.CharField(
                choices=[
                    ("diretor", "Diretor"),
                    ("vice_diretor", "Vice-Diretor"),
                    ("secretario", "Secretário"),
                    ("coordenador", "Coordenador"),
                ],
                help_text="Cargo do gestor",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="gestor",
            name="cep",
            field=models.CharField(blank=True, help_text="CEP", max_length=9),
        ),
        migrations.AlterField(
            model_name="gestor",
            name="cidade",
            field=models.CharField(blank=True, help_text="Cidade", max_length=100),
        ),
        migrations.AlterField(
            model_name="gestor",
            name="complemento",
            field=models.CharField(
                blank=True, help_text="Complemento do endereço", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="gestor",
            name="cpf",
            field=models.CharField(
                db_index=True,
                help_text="CPF no formato XXX.XXX.XXX-XX",
                max_length=14,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="gestor",
            name="criado_em",
            field=models.DateTimeField(auto_now_add=True, help_text="Data de criação"),
        ),
        migrations.AlterField(
            model_name="gestor",
            name="data_nascimento",
            field=models.DateField(
                blank=True, help_text="Data de nascimento", null=True
            ),
        ),
        migrations.AlterField(
            model_name="gestor",
            name="estado",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AC", "AC"),
                    ("AL", "AL"),
                    ("AP", "AP"),
                    ("AM", "AM"),
                    ("BA", "BA"),
                    ("CE", "CE"),
                    ("DF", "DF"),
                    ("ES", "ES"),
                    ("GO", "GO"),
                    ("MA", "MA"),
                    ("MT", "MT"),
                    ("MS", "MS"),
                    ("MG", "MG"),
                    ("PA", "PA"),
                    ("PB", "PB"),
                    ("PR", "PR"),
                    ("PE", "PE"),
                    ("PI", "PI"),
                    ("RJ", "RJ"),
                    ("RN", "RN"),
                    ("RS", "RS"),
                    ("RO", "RO"),
                    ("RR", "RR"),
                    ("SC", "SC"),
                    ("SP", "SP"),
                    ("SE", "SE"),
                    ("TO", "TO"),
                ],
                help_text="Estado (UF)",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="gestor",
            name="foto",
            field=models.ImageField(
                blank=True,
                help_text="Foto da pessoa",
                null=True,
                upload_to="fotos/pessoas/",
            ),
        ),
        migrations.AlterField(
            model_name="gestor",
            name="logradouro",
            field=models.CharField(blank=True, help_text="Logradouro", max_length=255),
        ),
        migrations.AlterField(
            model_name="gestor",
            name="nome_completo",
            field=models.CharField(help_text="Nome completo da pessoa", max_length=255),
        ),
        migrations.AlterField(
            model_name="gestor",
            name="numero",
            field=models.CharField(
                blank=True, help_text="Número do endereço", max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="gestor",
            name="telefone",
            field=models.CharField(
                blank=True, help_text="Número de telefone", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="gestor",
            name="user",
            field=models.OneToOneField(
                help_text="Usuário vinculado ao gestor",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gestor",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="gradehorario",
            name="turma",
            field=models.OneToOneField(
                help_text="Turma à qual esta grade pertence",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grade_horario",
                to="core.turma",
            ),
        ),
        migrations.AlterField(
            model_name="nota",
            name="aluno",
            field=models.ForeignKey(
                help_text="Aluno que recebeu a nota",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notas",
                to="core.aluno",
            ),
        ),
        migrations.AlterField(
            model_name="nota",
            name="data_lancamento",
            field=models.DateField(
                auto_now_add=True, help_text="Data de lançamento da nota"
            ),
        ),
        migrations.AlterField(
            model_name="nota",
            name="disciplina",
            field=models.ForeignKey(
                help_text="Disciplina à qual a nota pertence",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notas",
                to="core.disciplina",
            ),
        ),
        migrations.AlterField(
            model_name="nota",
            name="nota1",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Nota do primeiro bimestre",
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="nota",
            name="nota2",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Nota do segundo bimestre",
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="nota",
            name="nota3",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Nota do terceiro bimestre",
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="nota",
            name="nota4",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Nota do quarto bimestre",
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="nota",
            name="observacao",
            field=models.CharField(
                blank=True, help_text="Observações adicionais", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="professor",
            name="area_atuacao",
            field=models.CharField(
                blank=True, help_text="Área de atuação", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="professor",
            name="atualizado_em",
            field=models.DateTimeField(
                auto_now=True, help_text="Data da última atualização"
            ),
        ),
        migrations.AlterField(
            model_name="professor",
            name="bairro",
            field=models.CharField(blank=True, help_text="Bairro", max_length=100),
        ),
        migrations.AlterField(
            model_name="professor",
            name="cep",
            field=models.CharField(blank=True, help_text="CEP", max_length=9),
        ),
        migrations.AlterField(
            model_name="professor",
            name="cidade",
            field=models.CharField(blank=True, help_text="Cidade", max_length=100),
        ),
        migrations.AlterField(
            model_name="professor",
            name="complemento",
            field=models.CharField(
                blank=True, help_text="Complemento do endereço", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="professor",
            name="cpf",
            field=models.CharField(
                db_index=True,
                help_text="CPF no formato XXX.XXX.XXX-XX",
                max_length=14,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="professor",
            name="criado_em",
            field=models.DateTimeField(auto_now_add=True, help_text="Data de criação"),
        ),
        migrations.AlterField(
            model_name="professor",
            name="data_nascimento",
            field=models.DateField(
                blank=True, help_text="Data de nascimento", null=True
            ),
        ),
        migrations.AlterField(
            model_name="professor",
            name="especializacao",
            field=models.CharField(
                blank=True, help_text="Especialização", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="professor",
            name="estado",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AC", "AC"),
                    ("AL", "AL"),
                    ("AP", "AP"),
                    ("AM", "AM"),
                    ("BA", "BA"),
                    ("CE", "CE"),
                    ("DF", "DF"),
                    ("ES", "ES"),
                    ("GO", "GO"),
                    ("MA", "MA"),
                    ("MT", "MT"),
                    ("MS", "MS"),
                    ("MG", "MG"),
                    ("PA", "PA"),
                    ("PB", "PB"),
                    ("PR", "PR"),
                    ("PE", "PE"),
                    ("PI", "PI"),
                    ("RJ", "RJ"),
                    ("RN", "RN"),
                    ("RS", "RS"),
                    ("RO", "RO"),
                    ("RR", "RR"),
                    ("SC", "SC"),
                    ("SP", "SP"),
                    ("SE", "SE"),
                    ("TO", "TO"),
                ],
                help_text="Estado (UF)",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="professor",
            name="formacao",
            field=models.CharField(
                blank=True, help_text="Formação acadêmica", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="professor",
            name="foto",
            field=models.ImageField(
                blank=True,
                help_text="Foto da pessoa",
                null=True,
                upload_to="fotos/pessoas/",
            ),
        ),
        migrations.AlterField(
            model_name="professor",
            name="logradouro",
            field=models.CharField(blank=True, help_text="Logradouro", max_length=255),
        ),
        migrations.AlterField(
            model_name="professor",
            name="nome_completo",
            field=models.CharField(help_text="Nome completo da pessoa", max_length=255),
        ),
        migrations.AlterField(
            model_name="professor",
            name="numero",
            field=models.CharField(
                blank=True, help_text="Número do endereço", max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="professor",
            name="telefone",
            field=models.CharField(
                blank=True, help_text="Número de telefone", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="professor",
            name="user",
            field=models.OneToOneField(
                help_text="Usuário vinculado ao professor",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="professor",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="turma",
            name="ano",
            field=models.IntegerField(help_text="Ano da turma"),
        ),
        migrations.AlterField(
            model_name="turma",
            name="nome",
            field=models.CharField(help_text="Nome da turma", max_length=100),
        ),
        migrations.AlterField(
            model_name="turma",
            name="turno",
            field=models.CharField(
                choices=[("manha", "Manhã"), ("tarde", "Tarde"), ("noite", "Noite")],
                help_text="Turno da turma",
                max_length=20,
            ),
        ),
    ]
