# Generated by Django 5.0.5 on 2026-03-24 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_professor_options_professor_area_atuacao_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aluno",
            name="bairro",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="aluno",
            name="cep",
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AddField(
            model_name="aluno",
            name="complemento",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="aluno",
            name="data_nascimento",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="aluno",
            name="descricao_necessidade",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="aluno",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="aluno",
            name="filiacao1",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Nome do responsável 1"
            ),
        ),
        migrations.AddField(
            model_name="aluno",
            name="filiacao2",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Nome do responsável 2"
            ),
        ),
        migrations.AddField(
            model_name="aluno",
            name="logradouro",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="aluno",
            name="naturalidade",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="aluno",
            name="numero",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="aluno",
            name="possui_necessidade_especial",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="aluno",
            name="telefone",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
