# Generated by Django 6.0.3 on 2026-03-31 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_aluno_bairro_aluno_cep_aluno_complemento_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Frequencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField()),
                ("presente", models.BooleanField(default=True)),
                ("justificativa", models.TextField(blank=True)),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="frequencias",
                        to="core.aluno",
                    ),
                ),
                (
                    "disciplina",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="frequencias",
                        to="core.disciplina",
                    ),
                ),
            ],
            options={
                "verbose_name": "Frequência",
                "verbose_name_plural": "Frequências",
                "ordering": ["-data"],
                "unique_together": {("aluno", "disciplina", "data")},
            },
        ),
    ]
