# Generated by Django 6.0.3 on 2026-04-01 20:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_frequencia"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="frequencia",
            options={"ordering": ["-data"]},
        ),
        migrations.AlterModelOptions(
            name="professor",
            options={"ordering": ["nome_completo"]},
        ),
        migrations.AddField(
            model_name="gestor",
            name="cep",
            field=models.CharField(blank=True, max_length=9, verbose_name="CEP"),
        ),
        migrations.AddField(
            model_name="gestor",
            name="data_nascimento",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data de nascimento"
            ),
        ),
        migrations.AddField(
            model_name="gestor",
            name="email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="E-mail"),
        ),
        migrations.AddField(
            model_name="gestor",
            name="telefone",
            field=models.CharField(blank=True, max_length=20, verbose_name="Telefone"),
        ),
        migrations.AlterField(
            model_name="aluno",
            name="bairro",
            field=models.CharField(blank=True, max_length=100, verbose_name="Bairro"),
        ),
        migrations.AlterField(
            model_name="aluno",
            name="cep",
            field=models.CharField(blank=True, max_length=9, verbose_name="CEP"),
        ),
        migrations.AlterField(
            model_name="aluno",
            name="cidade",
            field=models.CharField(blank=True, max_length=100, verbose_name="Cidade"),
        ),
        migrations.AlterField(
            model_name="aluno",
            name="complemento",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Complemento"
            ),
        ),
        migrations.AlterField(
            model_name="aluno",
            name="cpf",
            field=models.CharField(
                max_length=14,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$"
                    )
                ],
                verbose_name="CPF",
            ),
        ),
        migrations.AlterField(
            model_name="aluno",
            name="data_nascimento",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data de nascimento"
            ),
        ),
        migrations.AlterField(
            model_name="aluno",
            name="descricao_necessidade",
            field=models.TextField(
                blank=True, verbose_name="Descrição da necessidade especial"
            ),
        ),
        migrations.AlterField(
            model_name="aluno",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="E-mail"
            ),
        ),
        migrations.AlterField(
            model_name="aluno",
            name="estado",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AC", "AC"),
                    ("AL", "AL"),
                    ("AP", "AP"),
                    ("AM", "AM"),
                    ("BA", "BA"),
                    ("CE", "CE"),
                    ("DF", "DF"),
                    ("ES", "ES"),
                    ("GO", "GO"),
                    ("MA", "MA"),
                    ("MT", "MT"),
                    ("MS", "MS"),
                    ("MG", "MG"),
                    ("PA", "PA"),
                    ("PB", "PB"),
                    ("PR", "PR"),
                    ("PE", "PE"),
                    ("PI", "PI"),
                    ("RJ", "RJ"),
                    ("RN", "RN"),
                    ("RS", "RS"),
                    ("RO", "RO"),
                    ("RR", "RR"),
                    ("SC", "SC"),
                    ("SP", "SP"),
                    ("SE", "SE"),
                    ("TO", "TO"),
                ],
                max_length=2,
                verbose_name="UF",
            ),
        ),
        migrations.AlterField(
            model_name="aluno",
            name="filiacao1",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Filiação 1"
            ),
        ),
        migrations.AlterField(
            model_name="aluno",
            name="filiacao2",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Filiação 2"
            ),
        ),
        migrations.AlterField(
            model_name="aluno",
            name="foto",
            field=models.ImageField(
                blank=True, null=True, upload_to="fotos/alunos/", verbose_name="Foto"
            ),
        ),
        migrations.AlterField(
            model_name="aluno",
            name="logradouro",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Logradouro"
            ),
        ),
        migrations.AlterField(
            model_name="aluno",
            name="naturalidade",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Naturalidade"
            ),
        ),
        migrations.AlterField(
            model_name="aluno",
            name="nome_completo",
            field=models.CharField(max_length=255, verbose_name="Nome completo"),
        ),
        migrations.AlterField(
            model_name="aluno",
            name="numero",
            field=models.CharField(blank=True, max_length=10, verbose_name="Número"),
        ),
        migrations.AlterField(
            model_name="aluno",
            name="possui_necessidade_especial",
            field=models.BooleanField(
                default=False, verbose_name="Possui necessidade especial"
            ),
        ),
        migrations.AlterField(
            model_name="aluno",
            name="telefone",
            field=models.CharField(blank=True, max_length=20, verbose_name="Telefone"),
        ),
        migrations.AlterField(
            model_name="gestor",
            name="atualizado_em",
            field=models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
        ),
        migrations.AlterField(
            model_name="gestor",
            name="cargo",
            field=models.CharField(
                choices=[
                    ("diretor", "Diretor"),
                    ("vice_diretor", "Vice-Diretor"),
                    ("secretario", "Secretário"),
                    ("coordenador", "Coordenador"),
                ],
                max_length=20,
                verbose_name="Cargo",
            ),
        ),
        migrations.AlterField(
            model_name="gestor",
            name="cidade",
            field=models.CharField(blank=True, max_length=100, verbose_name="Cidade"),
        ),
        migrations.AlterField(
            model_name="gestor",
            name="cpf",
            field=models.CharField(
                max_length=14,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$"
                    )
                ],
                verbose_name="CPF",
            ),
        ),
        migrations.AlterField(
            model_name="gestor",
            name="criado_em",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
        ),
        migrations.AlterField(
            model_name="gestor",
            name="endereco",
            field=models.CharField(blank=True, max_length=255, verbose_name="Endereço"),
        ),
        migrations.AlterField(
            model_name="gestor",
            name="foto",
            field=models.ImageField(
                blank=True, null=True, upload_to="fotos/gestores/", verbose_name="Foto"
            ),
        ),
        migrations.AlterField(
            model_name="gestor",
            name="nome_completo",
            field=models.CharField(max_length=150, verbose_name="Nome completo"),
        ),
        migrations.AlterField(
            model_name="gestor",
            name="uf",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AC", "AC"),
                    ("AL", "AL"),
                    ("AP", "AP"),
                    ("AM", "AM"),
                    ("BA", "BA"),
                    ("CE", "CE"),
                    ("DF", "DF"),
                    ("ES", "ES"),
                    ("GO", "GO"),
                    ("MA", "MA"),
                    ("MT", "MT"),
                    ("MS", "MS"),
                    ("MG", "MG"),
                    ("PA", "PA"),
                    ("PB", "PB"),
                    ("PR", "PR"),
                    ("PE", "PE"),
                    ("PI", "PI"),
                    ("RJ", "RJ"),
                    ("RN", "RN"),
                    ("RS", "RS"),
                    ("RO", "RO"),
                    ("RR", "RR"),
                    ("SC", "SC"),
                    ("SP", "SP"),
                    ("SE", "SE"),
                    ("TO", "TO"),
                ],
                max_length=2,
                verbose_name="UF",
            ),
        ),
        migrations.AlterField(
            model_name="professor",
            name="cpf",
            field=models.CharField(
                max_length=14,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="turma",
            name="turno",
            field=models.CharField(
                choices=[("manha", "Manhã"), ("tarde", "Tarde"), ("noite", "Noite")],
                max_length=20,
            ),
        ),
    ]
