# Generated by Django 6.0.3 on 2026-04-02 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_frequencia_options_alter_professor_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aluno",
            name="filiacao1",
        ),
        migrations.RemoveField(
            model_name="aluno",
            name="filiacao2",
        ),
        migrations.AddField(
            model_name="aluno",
            name="responsavel1",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Responsável 1"
            ),
        ),
        migrations.AddField(
            model_name="aluno",
            name="responsavel2",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Responsável 2"
            ),
        ),
    ]
