# Generated by Django 6.0.3 on 2026-04-15 22:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaBem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Categoria de Bem',
                'verbose_name_plural': 'Categorias de Bens',
            },
        ),
        migrations.CreateModel(
            name='ItemEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('unidade_medida', models.CharField(default='unidade', help_text='Ex: Caixa, Pacote, Unidade', max_length=20)),
                ('estoque_minimo', models.IntegerField(default=5)),
            ],
            options={
                'verbose_name': 'Item de Estoque',
                'verbose_name_plural': 'Itens de Estoque',
                'db_table': 'infra_item_estoque',
            },
        ),
        migrations.CreateModel(
            name='UnidadeEscolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.CharField(blank=True, max_length=255)),
                ('eh_sede', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Unidade Escolar',
                'verbose_name_plural': 'Unidades Escolares',
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída')], max_length=10)),
                ('quantidade', models.IntegerField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('justificativa', models.CharField(blank=True, max_length=255)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infraestrutura.itemestoque')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infraestrutura.unidadeescolar')),
            ],
            options={
                'verbose_name': 'Movimentação de Estoque',
                'verbose_name_plural': 'Movimentações de Estoque',
                'db_table': 'infra_movimentacao_estoque',
            },
        ),
        migrations.CreateModel(
            name='ItemPatrimonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tombamento', models.CharField(max_length=50, unique=True, verbose_name='Número de Patrimônio (Tombamento)')),
                ('nome', models.CharField(max_length=150)),
                ('estado_conservacao', models.CharField(choices=[('NOVO', 'Novo'), ('BOM', 'Bom'), ('REGULAR', 'Regular'), ('DANIFICADO', 'Danificado'), ('INSERVIVEL', 'Inservível')], default='BOM', max_length=20)),
                ('data_aquisicao', models.DateField(blank=True, null=True)),
                ('valor_aquisicao', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='infraestrutura.categoriabem')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='infraestrutura.unidadeescolar')),
            ],
            options={
                'verbose_name': 'Item de Patrimônio',
                'verbose_name_plural': 'Itens de Patrimônio',
                'db_table': 'infra_patrimonio',
            },
        ),
        migrations.CreateModel(
            name='SaldoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saldos', to='infraestrutura.itemestoque')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saldos', to='infraestrutura.unidadeescolar')),
            ],
            options={
                'verbose_name': 'Saldo em Estoque',
                'verbose_name_plural': 'Saldos em Estoque',
                'db_table': 'infra_saldo_estoque',
                'unique_together': {('item', 'unidade')},
            },
        ),
    ]
