# Generated by Django 6.0.3 on 2026-04-23 20:54

import apps.comum.utils.fields
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infraestrutura', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempatrimonio',
            name='valor_aquisicao',
            field=apps.comum.utils.fields.EncryptedDecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='unidadeescolar',
            name='endereco',
            field=apps.comum.utils.fields.EncryptedCharField(blank=True, max_length=1000),
        ),
        migrations.CreateModel(
            name='HistoricalItemPatrimonio',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('tombamento', models.CharField(db_index=True, max_length=50, verbose_name='Número de Patrimônio (Tombamento)')),
                ('nome', models.CharField(max_length=150)),
                ('estado_conservacao', models.CharField(choices=[('NOVO', 'Novo'), ('BOM', 'Bom'), ('REGULAR', 'Regular'), ('DANIFICADO', 'Danificado'), ('INSERVIVEL', 'Inservível')], default='BOM', max_length=20)),
                ('data_aquisicao', models.DateField(blank=True, null=True)),
                ('valor_aquisicao', apps.comum.utils.fields.EncryptedDecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('categoria', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='infraestrutura.categoriabem')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('unidade', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='infraestrutura.unidadeescolar')),
            ],
            options={
                'verbose_name': 'historical Item de Patrimônio',
                'verbose_name_plural': 'historical Itens de Patrimônio',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalUnidadeEscolar',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('endereco', apps.comum.utils.fields.EncryptedCharField(blank=True, max_length=1000)),
                ('eh_sede', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Unidade Escolar',
                'verbose_name_plural': 'historical Unidades Escolares',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
