# Generated by Django 6.0.3 on 2026-04-23 21:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infraestrutura', '0002_alter_itempatrimonio_valor_aquisicao_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalitempatrimonio',
            name='fatura_origem',
            field=models.CharField(blank=True, help_text='ID ou Nº da Fatura de Compra', max_length=100),
        ),
        migrations.AddField(
            model_name='historicalitempatrimonio',
            name='marca',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='historicalitempatrimonio',
            name='modelo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='historicalitempatrimonio',
            name='numero_serie',
            field=models.CharField(blank=True, max_length=100, verbose_name='Número de Série'),
        ),
        migrations.AddField(
            model_name='historicalitempatrimonio',
            name='responsavel',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itempatrimonio',
            name='fatura_origem',
            field=models.CharField(blank=True, help_text='ID ou Nº da Fatura de Compra', max_length=100),
        ),
        migrations.AddField(
            model_name='itempatrimonio',
            name='marca',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='itempatrimonio',
            name='modelo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='itempatrimonio',
            name='numero_serie',
            field=models.CharField(blank=True, max_length=100, verbose_name='Número de Série'),
        ),
        migrations.AddField(
            model_name='itempatrimonio',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bens_sob_custodia', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Ambiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ambientes', to='infraestrutura.unidadeescolar')),
            ],
            options={
                'verbose_name': 'Ambiente',
                'verbose_name_plural': 'Ambientes',
                'db_table': 'infra_ambiente',
            },
        ),
        migrations.AddField(
            model_name='historicalitempatrimonio',
            name='ambiente',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='infraestrutura.ambiente'),
        ),
        migrations.AddField(
            model_name='itempatrimonio',
            name='ambiente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens', to='infraestrutura.ambiente'),
        ),
        migrations.CreateModel(
            name='ManutencaoBem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_solicitacao', models.DateField(auto_now_add=True)),
                ('data_realizacao', models.DateField(blank=True, null=True)),
                ('descricao_problema', models.TextField()),
                ('servico_realizado', models.TextField(blank=True)),
                ('custo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('executor', models.CharField(help_text='Empresa ou técnico', max_length=200)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manutencoes', to='infraestrutura.itempatrimonio')),
            ],
            options={
                'verbose_name': 'Manutenção de Bem',
                'verbose_name_plural': 'Manutenções de Bens',
                'db_table': 'infra_manutencao',
            },
        ),
    ]
