# Generated by Django 6.0.3 on 2026-04-16 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saude', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtestadoMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='saude/atestados/', verbose_name='Arquivo do Atestado')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(verbose_name='Data de Fim')),
                ('descricao', models.TextField(blank=True, verbose_name='Observações do Aluno')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado')], default='PENDENTE', max_length=10)),
                ('comentario_gestor', models.TextField(blank=True, verbose_name='Comentário do Gestor')),
                ('data_submissao', models.DateTimeField(auto_now_add=True)),
                ('data_analise', models.DateTimeField(blank=True, null=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atestados', to='usuarios.aluno')),
                ('analisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atestados_analisados', to='usuarios.gestor')),
            ],
            options={
                'verbose_name': 'Atestado Médico',
                'verbose_name_plural': 'Atestados Médicos',
                'db_table': 'core_atestadomedico',
                'ordering': ['-data_submissao'],
            },
        ),
    ]
