# Generated by Django 6.0.3 on 2026-04-16 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saude', '0002_atestadomedico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atestadomedico',
            name='aluno',
        ),
        migrations.AddField(
            model_name='atestadomedico',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='atestados', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='atestadomedico',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Observações'),
        ),
    ]
