# Generated by Django 6.0.3 on 2026-04-13 23:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alternativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
                ('eh_correta', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'core_alternativa',
            },
        ),
        migrations.CreateModel(
            name='AtividadeProfessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título da Atividade/Prova', max_length=150)),
                ('tipo', models.CharField(choices=[('TRABALHO', 'Trabalho'), ('ATIVIDADE', 'Atividade'), ('PROVA', 'Prova')], default='TRABALHO', max_length=20)),
                ('data', models.DateField(help_text='Data do agendamento (para provas, deve coincidir com o calendário)')),
                ('prazo_final', models.DateTimeField(blank=True, help_text='Data e Hora limite para entrega (Obrigatório para Atividade/Trabalho)', null=True)),
                ('descricao', models.TextField(blank=True, help_text='Descrição detalhada')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Atividade de Professor',
                'verbose_name_plural': 'Atividades de Professores',
                'db_table': 'core_atividadeprofessor',
                'ordering': ['-data', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome da disciplina', max_length=100)),
            ],
            options={
                'verbose_name': 'Disciplina',
                'verbose_name_plural': 'Disciplinas',
                'db_table': 'core_disciplina',
            },
        ),
        migrations.CreateModel(
            name='EntregaAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='entregas/atividades/')),
                ('comentario_aluno', models.TextField(blank=True)),
                ('feedback_professor', models.TextField(blank=True, help_text='Feedback geral da correção')),
                ('status', models.CharField(choices=[('ENTREGUE', 'Entregue'), ('CORRIGIDO', 'Corrigido'), ('DEVOLVIDO', 'Devolvido')], default='ENTREGUE', max_length=20)),
                ('data_entrega', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'core_entregaatividade',
                'ordering': ['-data_entrega'],
            },
        ),
        migrations.CreateModel(
            name='Frequencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(help_text='Data da frequência')),
                ('presente', models.BooleanField(default=True, help_text='Presença (True) ou Falta (False)')),
                ('observacao', models.CharField(blank=True, help_text='Observações', max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Frequência',
                'verbose_name_plural': 'Frequências',
                'db_table': 'core_frequencia',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='GradeHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('segunda', 'Segunda-feira'), ('terca', 'Terça-feira'), ('quarta', 'Quarta-feira'), ('quinta', 'Quinta-feira'), ('sexta', 'Sexta-feira')], max_length=10)),
                ('horario', models.CharField(help_text='Ex: 07:00 - 07:50', max_length=20)),
            ],
            options={
                'verbose_name': 'Grade de Horário',
                'verbose_name_plural': 'Grades de Horários',
                'db_table': 'core_gradehorario',
                'ordering': ['horario', 'dia'],
            },
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota1', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('nota2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('nota3', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('nota4', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('observacao', models.CharField(blank=True, max_length=255)),
                ('data_lancamento', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
                'db_table': 'core_nota',
                'ordering': ['aluno', 'disciplina'],
            },
        ),
        migrations.CreateModel(
            name='NotaAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, help_text='Nota obtida na atividade', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('observacao', models.CharField(blank=True, max_length=255)),
                ('data_lancamento', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Nota de Atividade',
                'verbose_name_plural': 'Notas de Atividades',
                'db_table': 'core_notaatividade',
                'ordering': ['aluno', 'atividade'],
            },
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(help_text='Enunciado da questão')),
                ('tipo', models.CharField(choices=[('OBJETIVA', 'Objetiva (Múltipla Escolha)'), ('DISCURSIVA', 'Discursiva (Texto)')], default='OBJETIVA', max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, default=1.0, help_text='Valor em pontos desta questão', max_digits=5)),
                ('ordem', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Questão',
                'verbose_name_plural': 'Questões',
                'db_table': 'core_questao',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='RespostaAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_resposta', models.TextField(blank=True, help_text='Para questões discursivas', null=True)),
                ('comentario_professor', models.TextField(blank=True, help_text='Correção específica desta questão')),
                ('pontos_atribuidos', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'core_respostaaluno',
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome da turma', max_length=100)),
                ('turno', models.CharField(choices=[('manha', 'Manhã'), ('tarde', 'Tarde'), ('noite', 'Noite')], help_text='Turno da turma', max_length=20)),
                ('ano', models.IntegerField(help_text='Ano da turma')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
                'db_table': 'core_turma',
                'ordering': ['nome'],
            },
        ),
    ]
