# Generated by Django 6.0.3 on 2026-04-13 23:31
# Migração automática: não editar à mão; use makemigrations / migrate.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='professor',
            field=models.ForeignKey(help_text='Professor responsável', on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas', to='usuarios.professor'),
        ),
        migrations.AddField(
            model_name='atividadeprofessor',
            name='disciplina',
            field=models.ForeignKey(help_text='Disciplina associada', on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='academico.disciplina'),
        ),
        migrations.AddField(
            model_name='entregaatividade',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='usuarios.aluno'),
        ),
        migrations.AddField(
            model_name='entregaatividade',
            name='atividade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='academico.atividadeprofessor'),
        ),
        migrations.AddField(
            model_name='frequencia',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frequencias', to='usuarios.aluno'),
        ),
        migrations.AddField(
            model_name='frequencia',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frequencias', to='academico.disciplina'),
        ),
        migrations.AddField(
            model_name='gradehorario',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='academico.disciplina'),
        ),
        migrations.AddField(
            model_name='nota',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='usuarios.aluno'),
        ),
        migrations.AddField(
            model_name='nota',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='academico.disciplina'),
        ),
        migrations.AddField(
            model_name='notaatividade',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_atividades', to='usuarios.aluno'),
        ),
        migrations.AddField(
            model_name='notaatividade',
            name='atividade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_alunos', to='academico.atividadeprofessor'),
        ),
        migrations.AddField(
            model_name='questao',
            name='atividade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questoes', to='academico.atividadeprofessor'),
        ),
        migrations.AddField(
            model_name='alternativa',
            name='questao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternativas', to='academico.questao'),
        ),
        migrations.AddField(
            model_name='respostaaluno',
            name='alternativa_escolhida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academico.alternativa'),
        ),
        migrations.AddField(
            model_name='respostaaluno',
            name='entrega',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='academico.entregaatividade'),
        ),
        migrations.AddField(
            model_name='respostaaluno',
            name='questao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.questao'),
        ),
        migrations.AddField(
            model_name='gradehorario',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='academico.turma'),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='turma',
            field=models.ForeignKey(help_text='Turma associada', on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas', to='academico.turma'),
        ),
        migrations.AlterUniqueTogether(
            name='entregaatividade',
            unique_together={('aluno', 'atividade')},
        ),
        migrations.AlterUniqueTogether(
            name='frequencia',
            unique_together={('aluno', 'disciplina', 'data')},
        ),
        migrations.AlterUniqueTogether(
            name='nota',
            unique_together={('aluno', 'disciplina')},
        ),
        migrations.AlterUniqueTogether(
            name='notaatividade',
            unique_together={('aluno', 'atividade')},
        ),
        migrations.AlterUniqueTogether(
            name='gradehorario',
            unique_together={('turma', 'dia', 'horario')},
        ),
    ]
