# Generated by Django 6.0.3 on 2026-04-16 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0007_frequencia_atestado_frequencia_justificada'),
    ]

    operations = [
        migrations.AddField(
            model_name='planejamentoaula',
            name='status',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('SUSPENSA', 'Suspensa'), ('CANCELADA', 'Cancelada')], default='NORMAL', max_length=15),
        ),
    ]
