# Generated by Django 6.0.3 on 2026-04-16 22:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academico", "0008_planejamentoaula_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notificacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("NOTA", "Nota lançada"),
                            ("CHAMADA", "Chamada Realizada"),
                            ("CORRECAO", "Atividade Corrigida"),
                            ("GABARITO", "Gabarito Disponível"),
                            ("ENTREGA", "Nova Entrega de Atividade"),
                            ("ATESTADO", "Novo Atestado Enviado"),
                            ("SISTEMA", "Mensagem do Sistema"),
                            ("MENSAGEM", "Nova Mensagem"),
                        ],
                        max_length=20,
                    ),
                ),
                ("titulo", models.CharField(max_length=120)),
                ("mensagem", models.TextField()),
                ("url_destino", models.CharField(blank=True, max_length=255)),
                ("lida", models.BooleanField(default=False)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notificacoes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notificação",
                "verbose_name_plural": "Notificações",
                "db_table": "core_notificacao",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.DeleteModel(
            name="NotificacaoAluno",
        ),
    ]
