# Generated by Django 6.0.3 on 2026-04-22 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("academico", "0009_notificacao_delete_notificacaoaluno"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gradehorario",
            options={
                "ordering": ["dia", "horario"],
                "verbose_name": "Grade de Horário",
                "verbose_name_plural": "Grades de Horários",
            },
        ),
        migrations.AlterUniqueTogether(
            name="gradehorario",
            unique_together={("disciplina", "dia", "horario")},
        ),
    ]
