# Generated by Django 6.0.4 on 2026-05-16 13:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0012_turma_instituicao'),
        ('usuarios', '0011_alter_aluno_cpf_alter_gestor_cpf_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestaoBanco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.TextField()),
                ('nivel', models.CharField(choices=[('FACIL', 'Fácil'), ('MEDIO', 'Médio'), ('DIFICIL', 'Difícil')], default='MEDIO', max_length=10)),
                ('tipo', models.CharField(choices=[('MULTIPLA_ESCOLHA', 'Múltipla Escolha'), ('DISSERTATIVA', 'Dissertativa')], default='MULTIPLA_ESCOLHA', max_length=20)),
                ('tags', models.CharField(blank=True, help_text='Tags para busca (ex: Trigonometria, Revolução Francesa)', max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banco_questoes', to='academico.disciplina')),
            ],
            options={
                'verbose_name': 'Questão do Banco',
                'verbose_name_plural': 'Banco de Questões',
                'db_table': 'core_questao_banco',
            },
        ),
        migrations.CreateModel(
            name='ProvaGerada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('data_geracao', models.DateTimeField(auto_now_add=True)),
                ('slug_acesso', models.SlugField(blank=True, unique=True)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.disciplina')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.turma')),
                ('questoes', models.ManyToManyField(related_name='provas_geradas', to='academico.questaobanco')),
            ],
            options={
                'verbose_name': 'Prova Gerada',
                'verbose_name_plural': 'Provas Geradas',
                'db_table': 'core_prova_gerada',
            },
        ),
        migrations.CreateModel(
            name='AlternativaBanco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('correta', models.BooleanField(default=False)),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternativas', to='academico.questaobanco')),
            ],
            options={
                'db_table': 'core_alternativa_banco',
            },
        ),
        migrations.CreateModel(
            name='RubricaAvaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Trabalho em Equipe, Clareza Textual', max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('peso', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('nota', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('data_avaliacao', models.DateField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_rubricas', to='usuarios.aluno')),
            ],
            options={
                'verbose_name': 'Avaliação por Rubrica',
                'verbose_name_plural': 'Avaliações por Rubricas',
                'db_table': 'core_rubrica_avaliacao',
            },
        ),
    ]
