# Generated by Django 6.0.4 on 2026-05-16 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0013_questaobanco_provagerada_alternativabanco_and_more'),
        ('usuarios', '0011_alter_aluno_cpf_alter_gestor_cpf_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiscoEvasao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, help_text='Score de 0 a 100 (Quanto maior, maior o risco)', max_digits=5)),
                ('fatores', models.TextField(blank=True, help_text='Explicação dos fatores (ex: Baixa frequência, notas em queda)')),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('aluno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risco_evasao', to='usuarios.aluno')),
            ],
            options={
                'verbose_name': 'Risco de Evasão',
                'verbose_name_plural': 'Riscos de Evasão',
                'db_table': 'core_risco_evasao',
            },
        ),
    ]
