[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
build_flags =
    -I"$PROJECT_DIR/.platformio/packages/toolchain-xtensa-esp32/xtensa-esp32-elf/include/c++/11.2.0"
    -I"$PROJECT_DIR/.platformio/packages/toolchain-xtensa-esp32/xtensa-esp32-elf/include"
monitor_speed = 115200
lib_deps =
    miguelbalboa/MFRC522 @ ^1.4.11
    knolleary/PubSubClient @ ^2.8
