# Generated by Django 6.0.4 on 2026-05-16 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FunnelStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Etapa')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Etapa do Funil',
                'verbose_name_plural': 'Etapas do Funil',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Interessado')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('student_name', models.CharField(blank=True, max_length=255, verbose_name='Nome do Aluno')),
                ('student_grade', models.CharField(blank=True, max_length=100, verbose_name='Série de Interesse')),
                ('source', models.CharField(choices=[('site', 'Site / Formulário'), ('indicacao', 'Indicação'), ('redes_sociais', 'Redes Sociais'), ('presencial', 'Presencial'), ('outro', 'Outro')], default='site', max_length=50, verbose_name='Origem')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='leads.funnelstage', verbose_name='Etapa Atual')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
            },
        ),
        migrations.CreateModel(
            name='LeadInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('call', 'Ligação'), ('whatsapp', 'WhatsApp'), ('email', 'E-mail'), ('visit', 'Visita Presencial'), ('meeting', 'Reunião')], max_length=50, verbose_name='Tipo de Interação')),
                ('description', models.TextField(verbose_name='Descrição da Interação')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='leads.lead')),
            ],
            options={
                'verbose_name': 'Interação com Lead',
                'verbose_name_plural': 'Interações com Leads',
            },
        ),
    ]
