# Generated by Django 6.0.3 on 2026-04-23 00:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0002_add_status_matricula_aluno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_vencimento', models.DateField()),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('ATRASADO', 'Atrasado'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20)),
                ('link_pagamento', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faturas', to='usuarios.aluno')),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_pagamento', models.DateTimeField(default=django.utils.timezone.now)),
                ('metodo', models.CharField(choices=[('BOLETO', 'Boleto'), ('PIX', 'Pix'), ('CARTAO', 'Cartão de Crédito'), ('DINHEIRO', 'Dinheiro')], max_length=20)),
                ('comprovante', models.FileField(blank=True, null=True, upload_to='comprovantes/')),
                ('transacao_id', models.CharField(blank=True, max_length=100, null=True)),
                ('fatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='financeiro.fatura')),
            ],
        ),
    ]
