# Generated by Django 6.0.3 on 2026-04-23 21:43

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_alter_fatura_link_pagamento_and_more'),
        ('infraestrutura', '0003_historicalitempatrimonio_fatura_origem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('RECEITA', 'Receita'), ('DESPESA', 'Despesa')], max_length=10)),
                ('descricao', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Categoria Financeira',
                'verbose_name_plural': 'Categorias Financeiras',
                'db_table': 'fin_categoria',
            },
        ),
        migrations.CreateModel(
            name='CentroCusto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Centro de Custo',
                'verbose_name_plural': 'Centros de Custo',
                'db_table': 'fin_centro_custo',
            },
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='comprovante',
            field=models.FileField(blank=True, null=True, upload_to='financeiro/pagamentos/'),
        ),
        migrations.AlterModelTable(
            name='fatura',
            table='fin_fatura',
        ),
        migrations.AlterModelTable(
            name='pagamento',
            table='fin_pagamento_fatura',
        ),
        migrations.CreateModel(
            name='HistoricalLancamento',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída')], max_length=10)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_pagamento', models.DateField(default=django.utils.timezone.now)),
                ('descricao', models.CharField(max_length=255)),
                ('comprovante', models.TextField(blank=True, max_length=100, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('autorizado_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='financeiro.categoriafinanceira')),
                ('centro_custo', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='financeiro.centrocusto')),
                ('fatura_origem', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='financeiro.fatura')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('item_patrimonio', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='infraestrutura.itempatrimonio')),
            ],
            options={
                'verbose_name': 'historical Lançamento',
                'verbose_name_plural': 'historical Lançamentos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Lancamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída')], max_length=10)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_pagamento', models.DateField(default=django.utils.timezone.now)),
                ('descricao', models.CharField(max_length=255)),
                ('comprovante', models.FileField(blank=True, null=True, upload_to='financeiro/comprovantes/')),
                ('autorizado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='autorizacoes_fin', to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financeiro.categoriafinanceira')),
                ('centro_custo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.centrocusto')),
                ('fatura_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.fatura')),
                ('item_patrimonio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='infraestrutura.itempatrimonio')),
            ],
            options={
                'verbose_name': 'Lançamento',
                'verbose_name_plural': 'Lançamentos',
                'db_table': 'fin_lancamento',
            },
        ),
        migrations.CreateModel(
            name='FolhaPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_referencia', models.IntegerField()),
                ('ano_referencia', models.IntegerField()),
                ('salario_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('descontos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('impostos_encargos', models.DecimalField(decimal_places=2, default=0, help_text='INSS, FGTS, etc.', max_digits=10)),
                ('pago', models.BooleanField(default=False)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folhas_pagamento', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Folha de Pagamento',
                'verbose_name_plural': 'Folhas de Pagamento',
                'db_table': 'fin_folha_pagamento',
                'unique_together': {('funcionario', 'mes_referencia', 'ano_referencia')},
            },
        ),
    ]
