# Generated by Django 6.0.3 on 2026-04-27 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0001_initial'),
        ('financeiro', '0003_categoriafinanceira_centrocusto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriafinanceira',
            name='instituicao',
            field=models.ForeignKey(blank=True, help_text='Instituição à qual este registro pertence', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='comum.instituicao'),
        ),
        migrations.AddField(
            model_name='centrocusto',
            name='instituicao',
            field=models.ForeignKey(blank=True, help_text='Instituição à qual este registro pertence', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='comum.instituicao'),
        ),
        migrations.AddField(
            model_name='fatura',
            name='instituicao',
            field=models.ForeignKey(blank=True, help_text='Instituição à qual este registro pertence', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='comum.instituicao'),
        ),
        migrations.AddField(
            model_name='folhapagamento',
            name='instituicao',
            field=models.ForeignKey(blank=True, help_text='Instituição à qual este registro pertence', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='comum.instituicao'),
        ),
        migrations.AddField(
            model_name='historicalfatura',
            name='instituicao',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Instituição à qual este registro pertence', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='comum.instituicao'),
        ),
        migrations.AddField(
            model_name='historicallancamento',
            name='instituicao',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Instituição à qual este registro pertence', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='comum.instituicao'),
        ),
        migrations.AddField(
            model_name='lancamento',
            name='instituicao',
            field=models.ForeignKey(blank=True, help_text='Instituição à qual este registro pertence', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='comum.instituicao'),
        ),
    ]
