# Generated by Django 6.0.4 on 2026-05-16 13:55

import apps.comum.utils.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0001_initial'),
        ('financeiro', '0004_categoriafinanceira_instituicao_and_more'),
        ('usuarios', '0011_alter_aluno_cpf_alter_gestor_cpf_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcordoFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_total_original', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_com_desconto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('numero_parcelas', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('CONCLUIDO', 'Concluído'), ('QUEBRADO', 'Quebrado')], default='ATIVO', max_length=20)),
                ('data_acordo', models.DateTimeField(auto_now_add=True)),
                ('observacoes', models.TextField(blank=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acordos', to='usuarios.aluno')),
                ('faturas_originais', models.ManyToManyField(related_name='acordos_origem', to='financeiro.fatura')),
                ('instituicao', models.ForeignKey(blank=True, help_text='Instituição à qual este registro pertence', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='comum.instituicao')),
            ],
            options={
                'verbose_name': 'Acordo Financeiro',
                'verbose_name_plural': 'Acordos Financeiros',
                'db_table': 'fin_acordo',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('ASAAS', 'Asaas'), ('EFI', 'Efí (Gerencianet)'), ('STRIPE', 'Stripe')], max_length=50)),
                ('api_key', apps.comum.utils.fields.EncryptedCharField(max_length=500)),
                ('client_id', apps.comum.utils.fields.EncryptedCharField(blank=True, max_length=500, null=True)),
                ('webhook_secret', apps.comum.utils.fields.EncryptedCharField(blank=True, max_length=500, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('instituicao', models.ForeignKey(blank=True, help_text='Instituição à qual este registro pertence', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='comum.instituicao')),
            ],
            options={
                'verbose_name': 'Configuração de Gateway',
                'verbose_name_plural': 'Configurações de Gateways',
                'db_table': 'fin_config_gateway',
            },
        ),
        migrations.CreateModel(
            name='ParcelaAcordo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_vencimento', models.DateField()),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('ATRASADO', 'Atrasado'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20)),
                ('link_pagamento', apps.comum.utils.fields.EncryptedURLField(blank=True, max_length=1000, null=True)),
                ('acordo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='financeiro.acordofinanceiro')),
                ('instituicao', models.ForeignKey(blank=True, help_text='Instituição à qual este registro pertence', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='comum.instituicao')),
            ],
            options={
                'db_table': 'fin_parcela_acordo',
            },
        ),
    ]
