# Generated by Django 6.0.3 on 2026-05-06 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0001_initial'),
        ('seguranca', '0003_blacklistip_bugreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoSeguranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manutencao_ativa', models.BooleanField(default=False, verbose_name='Modo Manutenção Ativo')),
                ('mensagem_manutencao', models.TextField(default='O sistema está passando por uma manutenção programada para melhorias. Voltaremos em breve!', verbose_name='Mensagem de Manutenção')),
                ('permite_login_gestor', models.BooleanField(default=True, help_text='Se desativado, apenas Superusuários poderão acessar.', verbose_name='Permitir Login de Gestores em Manutenção')),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('instituicao', models.ForeignKey(blank=True, help_text='Instituição à qual este registro pertence', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='comum.instituicao')),
            ],
            options={
                'verbose_name': 'Configuração de Segurança',
                'verbose_name_plural': 'Configurações de Segurança',
            },
        ),
    ]
