# Generated by Django 6.0.3 on 2026-05-12 21:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguranca', '0004_configuracaoseguranca'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcessoDadosSensiveis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recurso', models.CharField(max_length=255, verbose_name='Recurso acessado (ex: Aluno #123)')),
                ('tipo_dado', models.CharField(max_length=100, verbose_name='Tipo de dado (ex: CPF, Financeiro)')),
                ('data_acesso', models.DateTimeField(auto_now_add=True)),
                ('ip_origem', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário que acessou')),
            ],
            options={
                'verbose_name': 'Acesso a Dados Sensíveis',
                'verbose_name_plural': 'Acessos a Dados Sensíveis',
                'ordering': ['-data_acesso'],
            },
        ),
    ]
