# Generated by Django 6.0.3 on 2026-05-12 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguranca', '0005_acessodadossensiveis'),
    ]

    operations = [
        migrations.AddField(
            model_name='logerro',
            name='resolvido',
            field=models.BooleanField(default=False),
        ),
    ]
