# Generated by Django 6.0.3 on 2026-05-13 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguranca', '0006_logerro_resolvido'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logerro',
            options={'ordering': ['-ultima_ocorrencia'], 'verbose_name': 'Log de Erro', 'verbose_name_plural': 'Logs de Erros'},
        ),
        migrations.AddField(
            model_name='logerro',
            name='contador',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='logerro',
            name='hash_erro',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='logerro',
            name='ultima_ocorrencia',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
