# Generated by Django 6.0.3 on 2026-05-13 23:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguranca', '0007_alter_logerro_options_logerro_contador_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bugreport',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chamados_atribuidos', to=settings.AUTH_USER_MODEL, verbose_name='Técnico Responsável'),
        ),
        migrations.AddField(
            model_name='bugreport',
            name='sla_limite',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Prazo SLA'),
        ),
    ]
