# Generated by Django 6.0.3 on 2026-04-27 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome da Instituição', max_length=255)),
                ('cnpj', models.CharField(help_text='CNPJ da Instituição', max_length=18, unique=True)),
                ('slug', models.SlugField(help_text='Identificador único para URL (ex: escola-padrao)', unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='instituicao/logos/')),
                ('ativo', models.BooleanField(default=True)),
                ('max_alunos', models.PositiveIntegerField(default=500, help_text='Limite de alunos para este contrato')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Instituição',
                'verbose_name_plural': 'Instituições',
            },
        ),
    ]
