# Generated by Django 6.0.3 on 2026-04-13 23:31
# Migração automática: não editar à mão; use makemigrations / migrate.

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(help_text='Nome completo da pessoa', max_length=255)),
                ('cpf', models.CharField(db_index=True, help_text='CPF no formato XXX.XXX.XXX-XX', max_length=14, unique=True, validators=[django.core.validators.RegexValidator('^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$')])),
                ('data_nascimento', models.DateField(blank=True, help_text='Data de nascimento', null=True)),
                ('telefone', models.CharField(blank=True, help_text='Número de telefone', max_length=20)),
                ('cep', models.CharField(blank=True, help_text='CEP', max_length=9)),
                ('estado', models.CharField(blank=True, choices=[('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PR', 'PR'), ('PE', 'PE'), ('PI', 'PI'), ('RJ', 'RJ'), ('RN', 'RN'), ('RS', 'RS'), ('RO', 'RO'), ('RR', 'RR'), ('SC', 'SC'), ('SP', 'SP'), ('SE', 'SE'), ('TO', 'TO')], help_text='Estado (UF)', max_length=2)),
                ('cidade', models.CharField(blank=True, help_text='Cidade', max_length=100)),
                ('bairro', models.CharField(blank=True, help_text='Bairro', max_length=100)),
                ('logradouro', models.CharField(blank=True, help_text='Logradouro', max_length=255)),
                ('numero', models.CharField(blank=True, help_text='Número do endereço', max_length=10)),
                ('complemento', models.CharField(blank=True, help_text='Complemento do endereço', max_length=255)),
                ('foto', models.ImageField(blank=True, help_text='Foto da pessoa', null=True, upload_to='fotos/pessoas/')),
                ('criado_em', models.DateTimeField(auto_now_add=True, help_text='Data de criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, help_text='Data da última atualização')),
                ('naturalidade', models.CharField(blank=True, help_text='Cidade de origem', max_length=100)),
                ('responsavel1', models.CharField(blank=True, help_text='Nome do responsável principal', max_length=255)),
                ('responsavel2', models.CharField(blank=True, help_text='Nome do segundo responsável', max_length=255)),
                ('possui_necessidade_especial', models.BooleanField(default=False, help_text='Indica se possui necessidade especial')),
                ('descricao_necessidade', models.TextField(blank=True, help_text='Descrição da necessidade especial')),
                ('turma', models.ForeignKey(help_text='Turma do aluno', on_delete=django.db.models.deletion.CASCADE, related_name='alunos', to='academico.turma')),
                ('user', models.OneToOneField(help_text='Usuário vinculado ao aluno', on_delete=django.db.models.deletion.CASCADE, related_name='aluno', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
                'db_table': 'core_aluno',
                'ordering': ['nome_completo'],
            },
        ),
        migrations.CreateModel(
            name='Gestor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(help_text='Nome completo da pessoa', max_length=255)),
                ('cpf', models.CharField(db_index=True, help_text='CPF no formato XXX.XXX.XXX-XX', max_length=14, unique=True, validators=[django.core.validators.RegexValidator('^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$')])),
                ('data_nascimento', models.DateField(blank=True, help_text='Data de nascimento', null=True)),
                ('telefone', models.CharField(blank=True, help_text='Número de telefone', max_length=20)),
                ('cep', models.CharField(blank=True, help_text='CEP', max_length=9)),
                ('estado', models.CharField(blank=True, choices=[('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PR', 'PR'), ('PE', 'PE'), ('PI', 'PI'), ('RJ', 'RJ'), ('RN', 'RN'), ('RS', 'RS'), ('RO', 'RO'), ('RR', 'RR'), ('SC', 'SC'), ('SP', 'SP'), ('SE', 'SE'), ('TO', 'TO')], help_text='Estado (UF)', max_length=2)),
                ('cidade', models.CharField(blank=True, help_text='Cidade', max_length=100)),
                ('bairro', models.CharField(blank=True, help_text='Bairro', max_length=100)),
                ('logradouro', models.CharField(blank=True, help_text='Logradouro', max_length=255)),
                ('numero', models.CharField(blank=True, help_text='Número do endereço', max_length=10)),
                ('complemento', models.CharField(blank=True, help_text='Complemento do endereço', max_length=255)),
                ('foto', models.ImageField(blank=True, help_text='Foto da pessoa', null=True, upload_to='fotos/pessoas/')),
                ('criado_em', models.DateTimeField(auto_now_add=True, help_text='Data de criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, help_text='Data da última atualização')),
                ('cargo', models.CharField(choices=[('diretor', 'Diretor'), ('vice_diretor', 'Vice-Diretor'), ('secretario', 'Secretário'), ('coordenador', 'Coordenador')], help_text='Cargo do gestor', max_length=20)),
                ('user', models.OneToOneField(help_text='Usuário vinculado ao gestor', on_delete=django.db.models.deletion.CASCADE, related_name='gestor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gestor',
                'verbose_name_plural': 'Gestores',
                'db_table': 'core_gestor',
                'ordering': ['nome_completo'],
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(help_text='Nome completo da pessoa', max_length=255)),
                ('cpf', models.CharField(db_index=True, help_text='CPF no formato XXX.XXX.XXX-XX', max_length=14, unique=True, validators=[django.core.validators.RegexValidator('^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$')])),
                ('data_nascimento', models.DateField(blank=True, help_text='Data de nascimento', null=True)),
                ('telefone', models.CharField(blank=True, help_text='Número de telefone', max_length=20)),
                ('cep', models.CharField(blank=True, help_text='CEP', max_length=9)),
                ('estado', models.CharField(blank=True, choices=[('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PR', 'PR'), ('PE', 'PE'), ('PI', 'PI'), ('RJ', 'RJ'), ('RN', 'RN'), ('RS', 'RS'), ('RO', 'RO'), ('RR', 'RR'), ('SC', 'SC'), ('SP', 'SP'), ('SE', 'SE'), ('TO', 'TO')], help_text='Estado (UF)', max_length=2)),
                ('cidade', models.CharField(blank=True, help_text='Cidade', max_length=100)),
                ('bairro', models.CharField(blank=True, help_text='Bairro', max_length=100)),
                ('logradouro', models.CharField(blank=True, help_text='Logradouro', max_length=255)),
                ('numero', models.CharField(blank=True, help_text='Número do endereço', max_length=10)),
                ('complemento', models.CharField(blank=True, help_text='Complemento do endereço', max_length=255)),
                ('foto', models.ImageField(blank=True, help_text='Foto da pessoa', null=True, upload_to='fotos/pessoas/')),
                ('criado_em', models.DateTimeField(auto_now_add=True, help_text='Data de criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, help_text='Data da última atualização')),
                ('formacao', models.CharField(blank=True, help_text='Formação acadêmica', max_length=255)),
                ('especializacao', models.CharField(blank=True, help_text='Especialização', max_length=255)),
                ('area_atuacao', models.CharField(blank=True, help_text='Área de atuação', max_length=255)),
                ('user', models.OneToOneField(help_text='Usuário vinculado ao professor', on_delete=django.db.models.deletion.CASCADE, related_name='professor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professores',
                'db_table': 'core_professor',
                'ordering': ['nome_completo'],
            },
        ),
    ]
