# Generated by Django 6.0.3 on 2026-04-23 20:54

import apps.comum.utils.fields
import apps.comum.utils.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0011_historicalfrequencia_historicalnota_and_more'),
        ('usuarios', '0002_add_status_matricula_aluno'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='complemento',
            field=apps.comum.utils.fields.EncryptedCharField(blank=True, help_text='Complemento do endereço', max_length=500),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='cpf',
            field=models.CharField(db_index=True, help_text='CPF no formato XXX.XXX.XXX-XX', max_length=14, unique=True, validators=[apps.comum.utils.validators.validar_cpf]),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='data_nascimento',
            field=apps.comum.utils.fields.EncryptedDateField(blank=True, help_text='Data de nascimento', null=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='logradouro',
            field=apps.comum.utils.fields.EncryptedCharField(blank=True, help_text='Logradouro', max_length=500),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='numero',
            field=apps.comum.utils.fields.EncryptedCharField(blank=True, help_text='Número do endereço', max_length=100),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='telefone',
            field=apps.comum.utils.fields.EncryptedCharField(blank=True, help_text='Número de telefone', max_length=100),
        ),
        migrations.AlterField(
            model_name='gestor',
            name='complemento',
            field=apps.comum.utils.fields.EncryptedCharField(blank=True, help_text='Complemento do endereço', max_length=500),
        ),
        migrations.AlterField(
            model_name='gestor',
            name='cpf',
            field=models.CharField(db_index=True, help_text='CPF no formato XXX.XXX.XXX-XX', max_length=14, unique=True, validators=[apps.comum.utils.validators.validar_cpf]),
        ),
        migrations.AlterField(
            model_name='gestor',
            name='data_nascimento',
            field=apps.comum.utils.fields.EncryptedDateField(blank=True, help_text='Data de nascimento', null=True),
        ),
        migrations.AlterField(
            model_name='gestor',
            name='logradouro',
            field=apps.comum.utils.fields.EncryptedCharField(blank=True, help_text='Logradouro', max_length=500),
        ),
        migrations.AlterField(
            model_name='gestor',
            name='numero',
            field=apps.comum.utils.fields.EncryptedCharField(blank=True, help_text='Número do endereço', max_length=100),
        ),
        migrations.AlterField(
            model_name='gestor',
            name='telefone',
            field=apps.comum.utils.fields.EncryptedCharField(blank=True, help_text='Número de telefone', max_length=100),
        ),
        migrations.AlterField(
            model_name='professor',
            name='complemento',
            field=apps.comum.utils.fields.EncryptedCharField(blank=True, help_text='Complemento do endereço', max_length=500),
        ),
        migrations.AlterField(
            model_name='professor',
            name='cpf',
            field=models.CharField(db_index=True, help_text='CPF no formato XXX.XXX.XXX-XX', max_length=14, unique=True, validators=[apps.comum.utils.validators.validar_cpf]),
        ),
        migrations.AlterField(
            model_name='professor',
            name='data_nascimento',
            field=apps.comum.utils.fields.EncryptedDateField(blank=True, help_text='Data de nascimento', null=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='logradouro',
            field=apps.comum.utils.fields.EncryptedCharField(blank=True, help_text='Logradouro', max_length=500),
        ),
        migrations.AlterField(
            model_name='professor',
            name='numero',
            field=apps.comum.utils.fields.EncryptedCharField(blank=True, help_text='Número do endereço', max_length=100),
        ),
        migrations.AlterField(
            model_name='professor',
            name='telefone',
            field=apps.comum.utils.fields.EncryptedCharField(blank=True, help_text='Número de telefone', max_length=100),
        ),
        migrations.CreateModel(
            name='HistoricalAluno',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nome_completo', models.CharField(help_text='Nome completo da pessoa', max_length=255)),
                ('cpf', models.CharField(db_index=True, help_text='CPF no formato XXX.XXX.XXX-XX', max_length=14, validators=[apps.comum.utils.validators.validar_cpf])),
                ('data_nascimento', apps.comum.utils.fields.EncryptedDateField(blank=True, help_text='Data de nascimento', null=True)),
                ('telefone', apps.comum.utils.fields.EncryptedCharField(blank=True, help_text='Número de telefone', max_length=100)),
                ('cep', models.CharField(blank=True, help_text='CEP', max_length=9)),
                ('estado', models.CharField(blank=True, choices=[('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PR', 'PR'), ('PE', 'PE'), ('PI', 'PI'), ('RJ', 'RJ'), ('RN', 'RN'), ('RS', 'RS'), ('RO', 'RO'), ('RR', 'RR'), ('SC', 'SC'), ('SP', 'SP'), ('SE', 'SE'), ('TO', 'TO')], help_text='Estado (UF)', max_length=2)),
                ('cidade', models.CharField(blank=True, help_text='Cidade', max_length=100)),
                ('bairro', models.CharField(blank=True, help_text='Bairro', max_length=100)),
                ('logradouro', apps.comum.utils.fields.EncryptedCharField(blank=True, help_text='Logradouro', max_length=500)),
                ('numero', apps.comum.utils.fields.EncryptedCharField(blank=True, help_text='Número do endereço', max_length=100)),
                ('complemento', apps.comum.utils.fields.EncryptedCharField(blank=True, help_text='Complemento do endereço', max_length=500)),
                ('foto', models.TextField(blank=True, help_text='Foto da pessoa', max_length=100, null=True)),
                ('criado_em', models.DateTimeField(blank=True, editable=False, help_text='Data de criação')),
                ('atualizado_em', models.DateTimeField(blank=True, editable=False, help_text='Data da última atualização')),
                ('naturalidade', models.CharField(blank=True, help_text='Cidade de origem', max_length=100)),
                ('responsavel1', models.CharField(blank=True, help_text='Nome do responsável principal', max_length=255)),
                ('responsavel2', models.CharField(blank=True, help_text='Nome do segundo responsável', max_length=255)),
                ('possui_necessidade_especial', models.BooleanField(default=False, help_text='Indica se possui necessidade especial')),
                ('descricao_necessidade', models.TextField(blank=True, help_text='Descrição da necessidade especial')),
                ('status_matricula', models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo'), ('EVADIDO', 'Evadido'), ('TRANSFERIDO', 'Transferido'), ('FORMADO', 'Formado')], default='ATIVO', help_text='Situação atual da matrícula do aluno', max_length=15)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('turma', models.ForeignKey(blank=True, db_constraint=False, help_text='Turma do aluno', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='academico.turma')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, help_text='Usuário vinculado ao aluno', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Aluno',
                'verbose_name_plural': 'historical Alunos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalGestor',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nome_completo', models.CharField(help_text='Nome completo da pessoa', max_length=255)),
                ('cpf', models.CharField(db_index=True, help_text='CPF no formato XXX.XXX.XXX-XX', max_length=14, validators=[apps.comum.utils.validators.validar_cpf])),
                ('data_nascimento', apps.comum.utils.fields.EncryptedDateField(blank=True, help_text='Data de nascimento', null=True)),
                ('telefone', apps.comum.utils.fields.EncryptedCharField(blank=True, help_text='Número de telefone', max_length=100)),
                ('cep', models.CharField(blank=True, help_text='CEP', max_length=9)),
                ('estado', models.CharField(blank=True, choices=[('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PR', 'PR'), ('PE', 'PE'), ('PI', 'PI'), ('RJ', 'RJ'), ('RN', 'RN'), ('RS', 'RS'), ('RO', 'RO'), ('RR', 'RR'), ('SC', 'SC'), ('SP', 'SP'), ('SE', 'SE'), ('TO', 'TO')], help_text='Estado (UF)', max_length=2)),
                ('cidade', models.CharField(blank=True, help_text='Cidade', max_length=100)),
                ('bairro', models.CharField(blank=True, help_text='Bairro', max_length=100)),
                ('logradouro', apps.comum.utils.fields.EncryptedCharField(blank=True, help_text='Logradouro', max_length=500)),
                ('numero', apps.comum.utils.fields.EncryptedCharField(blank=True, help_text='Número do endereço', max_length=100)),
                ('complemento', apps.comum.utils.fields.EncryptedCharField(blank=True, help_text='Complemento do endereço', max_length=500)),
                ('foto', models.TextField(blank=True, help_text='Foto da pessoa', max_length=100, null=True)),
                ('criado_em', models.DateTimeField(blank=True, editable=False, help_text='Data de criação')),
                ('atualizado_em', models.DateTimeField(blank=True, editable=False, help_text='Data da última atualização')),
                ('cargo', models.CharField(choices=[('diretor', 'Diretor'), ('vice_diretor', 'Vice-Diretor'), ('secretario', 'Secretário'), ('coordenador', 'Coordenador')], help_text='Cargo do gestor', max_length=20)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, help_text='Usuário vinculado ao gestor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Gestor',
                'verbose_name_plural': 'historical Gestores',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalProfessor',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nome_completo', models.CharField(help_text='Nome completo da pessoa', max_length=255)),
                ('cpf', models.CharField(db_index=True, help_text='CPF no formato XXX.XXX.XXX-XX', max_length=14, validators=[apps.comum.utils.validators.validar_cpf])),
                ('data_nascimento', apps.comum.utils.fields.EncryptedDateField(blank=True, help_text='Data de nascimento', null=True)),
                ('telefone', apps.comum.utils.fields.EncryptedCharField(blank=True, help_text='Número de telefone', max_length=100)),
                ('cep', models.CharField(blank=True, help_text='CEP', max_length=9)),
                ('estado', models.CharField(blank=True, choices=[('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PR', 'PR'), ('PE', 'PE'), ('PI', 'PI'), ('RJ', 'RJ'), ('RN', 'RN'), ('RS', 'RS'), ('RO', 'RO'), ('RR', 'RR'), ('SC', 'SC'), ('SP', 'SP'), ('SE', 'SE'), ('TO', 'TO')], help_text='Estado (UF)', max_length=2)),
                ('cidade', models.CharField(blank=True, help_text='Cidade', max_length=100)),
                ('bairro', models.CharField(blank=True, help_text='Bairro', max_length=100)),
                ('logradouro', apps.comum.utils.fields.EncryptedCharField(blank=True, help_text='Logradouro', max_length=500)),
                ('numero', apps.comum.utils.fields.EncryptedCharField(blank=True, help_text='Número do endereço', max_length=100)),
                ('complemento', apps.comum.utils.fields.EncryptedCharField(blank=True, help_text='Complemento do endereço', max_length=500)),
                ('foto', models.TextField(blank=True, help_text='Foto da pessoa', max_length=100, null=True)),
                ('criado_em', models.DateTimeField(blank=True, editable=False, help_text='Data de criação')),
                ('atualizado_em', models.DateTimeField(blank=True, editable=False, help_text='Data da última atualização')),
                ('formacao', models.CharField(blank=True, help_text='Formação acadêmica', max_length=255)),
                ('especializacao', models.CharField(blank=True, help_text='Especialização', max_length=255)),
                ('area_atuacao', models.CharField(blank=True, help_text='Área de atuação', max_length=255)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, help_text='Usuário vinculado ao professor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Professor',
                'verbose_name_plural': 'historical Professores',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
