# Generated by Django 6.0.3 on 2026-04-27 21:07

import apps.comum.utils.fields
import apps.comum.utils.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0001_initial'),
        ('usuarios', '0003_alter_aluno_complemento_alter_aluno_cpf_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='instituicao',
            field=models.ForeignKey(blank=True, help_text='Instituição à qual este registro pertence', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='comum.instituicao'),
        ),
        migrations.AddField(
            model_name='gestor',
            name='instituicao',
            field=models.ForeignKey(blank=True, help_text='Instituição à qual este registro pertence', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='comum.instituicao'),
        ),
        migrations.AddField(
            model_name='historicalaluno',
            name='instituicao',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Instituição à qual este registro pertence', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='comum.instituicao'),
        ),
        migrations.AddField(
            model_name='historicalgestor',
            name='instituicao',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Instituição à qual este registro pertence', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='comum.instituicao'),
        ),
        migrations.AddField(
            model_name='historicalprofessor',
            name='instituicao',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Instituição à qual este registro pertence', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='comum.instituicao'),
        ),
        migrations.AddField(
            model_name='professor',
            name='instituicao',
            field=models.ForeignKey(blank=True, help_text='Instituição à qual este registro pertence', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='comum.instituicao'),
        ),
        migrations.CreateModel(
            name='HistoricalResponsavel',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nome_completo', models.CharField(help_text='Nome completo da pessoa', max_length=255)),
                ('cpf', models.CharField(db_index=True, help_text='CPF no formato XXX.XXX.XXX-XX', max_length=14, validators=[apps.comum.utils.validators.validar_cpf])),
                ('data_nascimento', apps.comum.utils.fields.EncryptedDateField(blank=True, help_text='Data de nascimento', null=True)),
                ('telefone', apps.comum.utils.fields.EncryptedCharField(blank=True, help_text='Número de telefone', max_length=100)),
                ('cep', models.CharField(blank=True, help_text='CEP', max_length=9)),
                ('estado', models.CharField(blank=True, choices=[('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PR', 'PR'), ('PE', 'PE'), ('PI', 'PI'), ('RJ', 'RJ'), ('RN', 'RN'), ('RS', 'RS'), ('RO', 'RO'), ('RR', 'RR'), ('SC', 'SC'), ('SP', 'SP'), ('SE', 'SE'), ('TO', 'TO')], help_text='Estado (UF)', max_length=2)),
                ('cidade', models.CharField(blank=True, help_text='Cidade', max_length=100)),
                ('bairro', models.CharField(blank=True, help_text='Bairro', max_length=100)),
                ('logradouro', apps.comum.utils.fields.EncryptedCharField(blank=True, help_text='Logradouro', max_length=500)),
                ('numero', apps.comum.utils.fields.EncryptedCharField(blank=True, help_text='Número do endereço', max_length=100)),
                ('complemento', apps.comum.utils.fields.EncryptedCharField(blank=True, help_text='Complemento do endereço', max_length=500)),
                ('foto', models.TextField(blank=True, help_text='Foto da pessoa', max_length=100, null=True)),
                ('criado_em', models.DateTimeField(blank=True, editable=False, help_text='Data de criação')),
                ('atualizado_em', models.DateTimeField(blank=True, editable=False, help_text='Data da última atualização')),
                ('parentesco', models.CharField(blank=True, help_text='Vínculo com o aluno (Ex: Pai, Mãe, Tutor)', max_length=50)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('instituicao', models.ForeignKey(blank=True, db_constraint=False, help_text='Instituição à qual este registro pertence', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='comum.instituicao')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, help_text='Usuário vinculado ao responsável', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Responsável',
                'verbose_name_plural': 'historical Responsáveis',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(help_text='Nome completo da pessoa', max_length=255)),
                ('cpf', models.CharField(db_index=True, help_text='CPF no formato XXX.XXX.XXX-XX', max_length=14, unique=True, validators=[apps.comum.utils.validators.validar_cpf])),
                ('data_nascimento', apps.comum.utils.fields.EncryptedDateField(blank=True, help_text='Data de nascimento', null=True)),
                ('telefone', apps.comum.utils.fields.EncryptedCharField(blank=True, help_text='Número de telefone', max_length=100)),
                ('cep', models.CharField(blank=True, help_text='CEP', max_length=9)),
                ('estado', models.CharField(blank=True, choices=[('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PR', 'PR'), ('PE', 'PE'), ('PI', 'PI'), ('RJ', 'RJ'), ('RN', 'RN'), ('RS', 'RS'), ('RO', 'RO'), ('RR', 'RR'), ('SC', 'SC'), ('SP', 'SP'), ('SE', 'SE'), ('TO', 'TO')], help_text='Estado (UF)', max_length=2)),
                ('cidade', models.CharField(blank=True, help_text='Cidade', max_length=100)),
                ('bairro', models.CharField(blank=True, help_text='Bairro', max_length=100)),
                ('logradouro', apps.comum.utils.fields.EncryptedCharField(blank=True, help_text='Logradouro', max_length=500)),
                ('numero', apps.comum.utils.fields.EncryptedCharField(blank=True, help_text='Número do endereço', max_length=100)),
                ('complemento', apps.comum.utils.fields.EncryptedCharField(blank=True, help_text='Complemento do endereço', max_length=500)),
                ('foto', models.ImageField(blank=True, help_text='Foto da pessoa', null=True, upload_to='fotos/pessoas/')),
                ('criado_em', models.DateTimeField(auto_now_add=True, help_text='Data de criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, help_text='Data da última atualização')),
                ('parentesco', models.CharField(blank=True, help_text='Vínculo com o aluno (Ex: Pai, Mãe, Tutor)', max_length=50)),
                ('alunos', models.ManyToManyField(help_text='Alunos sob responsabilidade deste perfil', related_name='responsaveis', to='usuarios.aluno')),
                ('instituicao', models.ForeignKey(blank=True, help_text='Instituição à qual este registro pertence', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='comum.instituicao')),
                ('user', models.OneToOneField(help_text='Usuário vinculado ao responsável', on_delete=django.db.models.deletion.CASCADE, related_name='responsavel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Responsável',
                'verbose_name_plural': 'Responsáveis',
                'db_table': 'core_responsavel',
                'ordering': ['nome_completo'],
            },
        ),
    ]
