# Generated by Django 6.0.3 on 2026-05-11 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0008_force_historical_date_to_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="aluno",
            name="matricula",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Matrícula única do aluno (Padrão: YYYYTTTUUUU)",
                max_length=12,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalaluno",
            name="matricula",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Matrícula única do aluno (Padrão: YYYYTTTUUUU)",
                max_length=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalresponsavel",
            name="controle_parental_ativo",
            field=models.BooleanField(
                default=False,
                help_text="Se ativado, o responsável recebe notificações em tempo real e pode restringir acessos.",
            ),
        ),
        migrations.AddField(
            model_name="historicalresponsavel",
            name="limite_diario_minutos",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Tempo máximo de uso do sistema pelo aluno por dia (0 para ilimitado).",
            ),
        ),
        migrations.AddField(
            model_name="responsavel",
            name="controle_parental_ativo",
            field=models.BooleanField(
                default=False,
                help_text="Se ativado, o responsável recebe notificações em tempo real e pode restringir acessos.",
            ),
        ),
        migrations.AddField(
            model_name="responsavel",
            name="limite_diario_minutos",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Tempo máximo de uso do sistema pelo aluno por dia (0 para ilimitado).",
            ),
        ),
    ]
