# Generated by Django 6.0.3 on 2026-05-11 23:34

import apps.comum.utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_aluno_matricula_historicalaluno_matricula_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='numero',
            field=apps.comum.utils.fields.EncryptedCharField(blank=True, help_text='Número do endereço', max_length=255),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='telefone',
            field=apps.comum.utils.fields.EncryptedCharField(blank=True, help_text='Número de telefone', max_length=255),
        ),
        migrations.AlterField(
            model_name='gestor',
            name='numero',
            field=apps.comum.utils.fields.EncryptedCharField(blank=True, help_text='Número do endereço', max_length=255),
        ),
        migrations.AlterField(
            model_name='gestor',
            name='telefone',
            field=apps.comum.utils.fields.EncryptedCharField(blank=True, help_text='Número de telefone', max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalaluno',
            name='numero',
            field=apps.comum.utils.fields.EncryptedCharField(blank=True, help_text='Número do endereço', max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalaluno',
            name='telefone',
            field=apps.comum.utils.fields.EncryptedCharField(blank=True, help_text='Número de telefone', max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalgestor',
            name='numero',
            field=apps.comum.utils.fields.EncryptedCharField(blank=True, help_text='Número do endereço', max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalgestor',
            name='telefone',
            field=apps.comum.utils.fields.EncryptedCharField(blank=True, help_text='Número de telefone', max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalprofessor',
            name='numero',
            field=apps.comum.utils.fields.EncryptedCharField(blank=True, help_text='Número do endereço', max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalprofessor',
            name='telefone',
            field=apps.comum.utils.fields.EncryptedCharField(blank=True, help_text='Número de telefone', max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalresponsavel',
            name='numero',
            field=apps.comum.utils.fields.EncryptedCharField(blank=True, help_text='Número do endereço', max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalresponsavel',
            name='telefone',
            field=apps.comum.utils.fields.EncryptedCharField(blank=True, help_text='Número de telefone', max_length=255),
        ),
        migrations.AlterField(
            model_name='professor',
            name='numero',
            field=apps.comum.utils.fields.EncryptedCharField(blank=True, help_text='Número do endereço', max_length=255),
        ),
        migrations.AlterField(
            model_name='professor',
            name='telefone',
            field=apps.comum.utils.fields.EncryptedCharField(blank=True, help_text='Número de telefone', max_length=255),
        ),
        migrations.AlterField(
            model_name='responsavel',
            name='numero',
            field=apps.comum.utils.fields.EncryptedCharField(blank=True, help_text='Número do endereço', max_length=255),
        ),
        migrations.AlterField(
            model_name='responsavel',
            name='telefone',
            field=apps.comum.utils.fields.EncryptedCharField(blank=True, help_text='Número de telefone', max_length=255),
        ),
    ]
