# Generated by Django 6.0.3 on 2026-05-13 22:45

import apps.comum.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_alter_aluno_numero_alter_aluno_telefone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='cpf',
            field=models.CharField(blank=True, db_index=True, help_text='CPF no formato XXX.XXX.XXX-XX', max_length=14, null=True, unique=True, validators=[apps.comum.utils.validators.validar_cpf]),
        ),
        migrations.AlterField(
            model_name='gestor',
            name='cpf',
            field=models.CharField(blank=True, db_index=True, help_text='CPF no formato XXX.XXX.XXX-XX', max_length=14, null=True, unique=True, validators=[apps.comum.utils.validators.validar_cpf]),
        ),
        migrations.AlterField(
            model_name='historicalaluno',
            name='cpf',
            field=models.CharField(blank=True, db_index=True, help_text='CPF no formato XXX.XXX.XXX-XX', max_length=14, null=True, validators=[apps.comum.utils.validators.validar_cpf]),
        ),
        migrations.AlterField(
            model_name='historicalgestor',
            name='cpf',
            field=models.CharField(blank=True, db_index=True, help_text='CPF no formato XXX.XXX.XXX-XX', max_length=14, null=True, validators=[apps.comum.utils.validators.validar_cpf]),
        ),
        migrations.AlterField(
            model_name='historicalprofessor',
            name='cpf',
            field=models.CharField(blank=True, db_index=True, help_text='CPF no formato XXX.XXX.XXX-XX', max_length=14, null=True, validators=[apps.comum.utils.validators.validar_cpf]),
        ),
        migrations.AlterField(
            model_name='historicalresponsavel',
            name='cpf',
            field=models.CharField(blank=True, db_index=True, help_text='CPF no formato XXX.XXX.XXX-XX', max_length=14, null=True, validators=[apps.comum.utils.validators.validar_cpf]),
        ),
        migrations.AlterField(
            model_name='professor',
            name='cpf',
            field=models.CharField(blank=True, db_index=True, help_text='CPF no formato XXX.XXX.XXX-XX', max_length=14, null=True, unique=True, validators=[apps.comum.utils.validators.validar_cpf]),
        ),
        migrations.AlterField(
            model_name='responsavel',
            name='cpf',
            field=models.CharField(blank=True, db_index=True, help_text='CPF no formato XXX.XXX.XXX-XX', max_length=14, null=True, unique=True, validators=[apps.comum.utils.validators.validar_cpf]),
        ),
    ]
