# Generated by Django 6.0.3 on 2026-05-12 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ti', '0002_ti_grupos_permissoes'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Identificador (slug)')),
                ('descricao', models.TextField(blank=True, verbose_name='Para que serve?')),
                ('ativo', models.BooleanField(default=True, verbose_name='Está ativo?')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('ultima_alteracao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Feature Flag',
                'verbose_name_plural': 'Feature Flags',
                'ordering': ['nome'],
            },
        ),
    ]
