# Generated by Django 6.0.3 on 2026-05-12 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ti', '0003_featureflag'),
    ]

    operations = [
        migrations.CreateModel(
            name='JanelaManutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('inicio', models.DateTimeField()),
                ('fim', models.DateTimeField()),
                ('bloquear_acesso', models.BooleanField(default=True, help_text='Impede login de usuários não-TI durante o período.')),
                ('aviso_banner', models.BooleanField(default=True, help_text='Exibir banner de aviso 24h antes.')),
                ('concluida', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Janela de Manutenção',
                'verbose_name_plural': 'Janelas de Manutenção',
                'ordering': ['-inicio'],
            },
        ),
        migrations.AlterModelOptions(
            name='politicati',
            options={},
        ),
        migrations.AddField(
            model_name='politicati',
            name='conteudo',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='politicati',
            name='rotulo',
            field=models.CharField(max_length=100),
        ),
    ]
