# Generated by Django 6.0.3 on 2026-05-12 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ti', '0004_janelamanutencao_alter_politicati_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvisoGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('mensagem', models.TextField()),
                ('tipo', models.CharField(choices=[('INFO', 'Informativo'), ('ALERTA', 'Alerta'), ('CRITICO', 'Crítico')], default='INFO', max_length=10)),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('expira_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Aviso Global',
                'verbose_name_plural': 'Avisos Globais',
            },
        ),
        migrations.CreateModel(
            name='ParametroSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=100, unique=True)),
                ('valor', models.TextField()),
                ('descricao', models.TextField(blank=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Parâmetro do Sistema',
                'verbose_name_plural': 'Parâmetros do Sistema',
            },
        ),
        migrations.AlterField(
            model_name='janelamanutencao',
            name='aviso_banner',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='janelamanutencao',
            name='bloquear_acesso',
            field=models.BooleanField(default=True),
        ),
    ]
