# Generated by Django 6.0.3 on 2026-05-12 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ti', '0005_avisoglobal_parametrosistema_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.CharField(max_length=255)),
                ('tamanho_bytes', models.BigIntegerField(default=0)),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SUCESSO', 'Sucesso'), ('FALHA', 'Falha'), ('EM_CURSO', 'Em Curso')], default='EM_CURSO', max_length=15)),
                ('storage_path', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name': 'Log de Backup',
                'verbose_name_plural': 'Logs de Backups',
                'ordering': ['-data_inicio'],
            },
        ),
    ]
