# Generated by Django 6.0.4 on 2026-05-16 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ti', '0006_logbackup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AtivoTi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('categoria', models.CharField(choices=[('HARDWARE', 'Hardware'), ('SOFTWARE', 'Software/Licença'), ('REDE', 'Equipamento de Rede'), ('PERIFERICO', 'Periférico')], max_length=20)),
                ('patrimonio', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('numero_serie', models.CharField(blank=True, max_length=100)),
                ('localizacao', models.CharField(help_text='Ex: Sala de Informática, Secretaria', max_length=200)),
                ('status', models.CharField(choices=[('ATIVO', 'Em Uso'), ('MANUTENCAO', 'Em Manutenção'), ('ESTOQUE', 'Em Estoque'), ('BAIXADO', 'Baixado/Sucata')], default='ATIVO', max_length=20)),
                ('data_aquisicao', models.DateField(blank=True, null=True)),
                ('valor_compra', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notas', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Ativo de TI',
                'verbose_name_plural': 'Ativos de TI',
            },
        ),
        migrations.CreateModel(
            name='ChamadoTi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('prioridade', models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Média'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='MEDIA', max_length=10)),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('EM_ATENDIMENTO', 'Em Atendimento'), ('AGUARDANDO_TERCEIRO', 'Aguardando Terceiro'), ('RESOLVIDO', 'Resolvido'), ('FECHADO', 'Fechado')], default='ABERTO', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('data_resolucao', models.DateTimeField(blank=True, null=True)),
                ('solucao', models.TextField(blank=True)),
                ('ativo_relacionado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ti.ativoti')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chamados_ti_abertos', to=settings.AUTH_USER_MODEL)),
                ('tecnico_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chamados_ti_atribuidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chamado de TI',
                'verbose_name_plural': 'Chamados de TI',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
