# Generated by Django 6.0.4 on 2026-05-16 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ti', '0007_ativoti_chamadoti'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CofreSegredo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servico', models.CharField(max_length=100, unique=True)),
                ('chave_publica', models.CharField(blank=True, max_length=255)),
                ('valor_criptografado', models.TextField()),
                ('descricao', models.TextField(blank=True)),
                ('ultima_leitura', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Cofre de Segredo',
                'verbose_name_plural': 'Cofre de Segredos',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoSeguranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloqueio_geografico', models.CharField(choices=[('NENHUM', 'Nenhum'), ('SOMENTE_BR', 'Somente Brasil'), ('LISTA_NEGRA', 'Bloquear Lista Negra')], default='NENHUM', max_length=20)),
                ('paises_bloqueados', models.TextField(blank=True, help_text='Códigos ISO separados por vírgula (Ex: US,CN,RU)')),
                ('limite_download_mb_minuto', models.PositiveIntegerField(default=100, help_text='Alerta de exfiltração se ultrapassado')),
                ('alerta_fingerprint_novo', models.BooleanField(default=True, verbose_name='Alertar novo dispositivo')),
                ('honeypot_ativo', models.BooleanField(default=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração SOC',
                'verbose_name_plural': 'Configurações SOC',
            },
        ),
        migrations.CreateModel(
            name='HoneyToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_arquivo', models.CharField(max_length=100)),
                ('caminho_fake', models.CharField(max_length=255)),
                ('total_acessos', models.PositiveIntegerField(default=0)),
                ('ultimo_acesso', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegraWAF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('padrao_regex', models.CharField(help_text='Regex para detectar ataque (Ex: SELECT|DROP|UNION)', max_length=255)),
                ('acao', models.CharField(choices=[('BLOQUEAR', 'Bloquear IP'), ('LOGAR', 'Apenas Logar')], default='BLOQUEAR', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FingerprintDispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assinatura_hash', models.CharField(max_length=64)),
                ('navegador', models.CharField(max_length=255)),
                ('sistema_operacional', models.CharField(max_length=100)),
                ('confiavel', models.BooleanField(default=False)),
                ('data_visto', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'assinatura_hash')},
            },
        ),
    ]
