# Generated by Django 6.0.3 on 2026-04-15 22:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comunicado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('conteudo', models.TextField(verbose_name='Conteúdo')),
                ('data_publicacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Publicação')),
                ('data_expiracao', models.DateField(blank=True, null=True, verbose_name='Data de Expiração')),
                ('publico_alvo', models.CharField(choices=[('GLOBAL', 'Global (Todos)'), ('ALUNOS', 'Apenas Alunos'), ('PROFESSORES', 'Apenas Professores'), ('GESTORES', 'Apenas Gestores')], default='GLOBAL', max_length=20, verbose_name='Público Alvo')),
                ('importancia', models.CharField(choices=[('NORMAL', 'Normal'), ('ALTA', 'Alta / Urgente')], default='NORMAL', max_length=20)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comunicados_criados', to='usuarios.gestor')),
            ],
            options={
                'verbose_name': 'Comunicado',
                'verbose_name_plural': 'Comunicados',
                'db_table': 'core_comunicado',
                'ordering': ['-data_publicacao'],
            },
        ),
    ]
