# Generated by Django 6.0.3 on 2026-04-15 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=200)),
                ('isbn', models.CharField(blank=True, max_length=20, null=True, verbose_name='ISBN')),
                ('ano_publicacao', models.IntegerField(blank=True, null=True)),
                ('editora', models.CharField(blank=True, max_length=100, null=True)),
                ('capa', models.ImageField(blank=True, null=True, upload_to='biblioteca/capas/')),
                ('quantidade_total', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emprestimo', models.DateField(auto_now_add=True)),
                ('data_devolucao_prevista', models.DateField()),
                ('data_devolucao_real', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('DEVOLVIDO', 'Devolvido'), ('ATRASADO', 'Atrasado'), ('RESERVA', 'Reserva')], default='ATIVO', max_length=10)),
                ('usuario_aluno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.aluno')),
                ('usuario_professor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.professor')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprestimos', to='biblioteca.livro')),
            ],
        ),
    ]
