# Generated by Django 6.0.3 on 2026-04-16 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='status_leitura',
            field=models.CharField(choices=[('NAO_INFORMADO', 'Apenas Devolvido'), ('LENDO', 'Estava Lendo'), ('FINALIZADO', 'Finalizou a Leitura')], default='NAO_INFORMADO', max_length=15, verbose_name='Status de Leitura'),
        ),
    ]
