# Generated by Django 6.0.3 on 2026-04-21 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0004_livro_data_cadastro'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='estado_conservacao',
            field=models.CharField(blank=True, choices=[('OTIMO', 'Ótimo / Perfeito'), ('RAZOAVEL', 'Razoável / Uso normal'), ('DANIFICADO', 'Danificado / Requer reparo')], max_length=10, null=True, verbose_name='Estado de Conservação na Devolução'),
        ),
    ]
